### ISSUE TITLE
setGasLimit(myGasLimit) not a function == Ethereum 

### ISSUE THREAD

**Issue by KBryan** [reach-sh/reach-lang#103]
Step to reproduce:
- Forked newest copy of Reach Repo
- Performed Reach update
- used example remote from examples folder

Current Hashes
reach: fde318f5
ethereum-devnet: fde318f5
algorand-devnet: fde318f5
runner: fde318f5
react-runner: fde318f5
rpc-server: fde318f5

**Comment by DanBurton** [comment]
What command are you using to run the example?

**Comment by KBryan** [comment]
REACH_CONNECTOR_MODE=ETH ../../reach run

**Comment by DanBurton** [comment]
I'm not able to reproduce this issue. It's possible that it isn't rebuilding the example based on the latest images. Can you try `../../reach clean` inside of the `examples/remote/` directory and see if that makes it work?

**Comment by DanBurton** [comment]
I have double checked that the ETH stdlib Accounts have the `setGasLimit` method on them.

If you are seeing "is not a function" errors, this sometimes indicates that you forgot to `await` a Promise.

```
const acc = stdlib.createAccount();
acc.setGasLimit(50000); // acc is a Promise, this is an error because Promise does not have this method.
```

```
const acc = await stdlib.createAccount();
acc.setGasLimit(50000); // this works because Account does have this method.
```
