### ISSUE TITLE
Tell user to cd to workshop folder

### ISSUE THREAD

**Issue by hagenhaus** [reach-sh/reach-lang#105]
In workshops 1-5, the directions tell the user to `mkdir` the workshop directory, and then, assuming that the user has changed directory into the new directory, the directions tell the user to run `../reach version` to verify that the script will run. Perhaps we should be more explicit so that copy/paste users don't get tripped up.

Tutorial 2.1 avoids this confusion by using `mkdir -p ~/reach/tut && cd ~/reach/tut`. This approach is probably the most bang for the least buck. This involves a change to `lib-rkt`.

Another approach might be to use `~/reach/reach` throughout.

One more idea to consider: Currently, `reach-lang` has a particular directory structure. I can `git clone` it to my computer, `cd` to any tutorial or workshop, and run the example using `~/reach-lang/reach`. I can add same to my `path` variable. I can also set my VSCode Reach IDE extension `Executable Location` variable to same. We could use this same directory structure for our "learning" directory structure, but change the root directory name from `reach-lang` to something else. We could choose `reach-learn`, but I think it is too similar to `reach-lang`. A better choice, perhaps, might be `reach-study`. Thx.

**Comment by jeapostrophe** [comment]
Thanks, I adjusted the `workshop-init` function

**Comment by hagenhaus** [comment]
Thanks, Jay.
