### ISSUE TITLE
Reach Standard Library call local instance of Algorand 

### ISSUE THREAD

**Issue by KBryan** [reach-sh/reach-lang#107]
On launching a dApp to Algorand mainnet it seems that the standard library calls a local instance of algod.

![Screen Shot 2021-04-27 at 9 14 36 AM](https://user-images.githubusercontent.com/681817/116422481-cc444700-a80d-11eb-8d37-27cbdf6b8654.png)

**Comment by jeapostrophe** [comment]
That looks to me like the indexer is not set correctly? I believe that @DanBurton will shortly be sending something to elaborate what's going on here

**Comment by DanBurton** [comment]
I'm working on improving the ergonomics of this. You can do something like the following:

```
import * as reach from '@reach-sh/stdlib/ALGO';
import algosdk from 'algosdk';
​​
const RANDLABS_PORT = ''; 
const RANDLABS_BASE = 'https://algoexplorerapi.io';
// const RANDLABS_BASE = 'https://testnet.algoexplorerapi.io';
// const RANDLABS_BASE = 'https://betanet.algoexplorerapi.io';
​
const ALGO_SERVER = RANDLABS_BASE;
const ALGO_PORT = RANDLABS_PORT;
const ALGO_TOKEN = '';
const ALGO_INDEXER_SERVER = `${RANDLABS_BASE}/idx2`;
const ALGO_INDEXER_PORT = RANDLABS_PORT;
const ALGO_INDEXER_TOKEN = '';
​
const algodClient = new algosdk.Algodv2(ALGO_TOKEN, ALGO_SERVER, ALGO_PORT);
const indexer = new algosdk.Indexer(ALGO_INDEXER_TOKEN, ALGO_INDEXER_SERVER, ALGO_INDEXER_PORT);
​
reach.setAlgodClient(algodClient);
reach.setIndexer(indexer);
```

I use the randlabs APIs in this example, but you can just as easily use PureStake, or any other API provider.

This currently only works with the `'mnemonic'` signing strategy, but I'm working on getting it to work with the `'AlgoSigner'` signing strategy as well.

I'll provide updates on this issue when:

* I have it working w/ AlgoSigner on MainNet/TestNet
* I have finished publishing and documenting the more ergonomic solution

**Comment by DanBurton** [comment]
This is now documented:

https://docs.reach.sh/ref-frontends-js-provider.html

The ergonomic solution is:

```
reach.setProviderByName('MainNet');
```

And it does work with AlgoSigner. =]
