### ISSUE TITLE
Compiler Error, "Not your program" - solc: stack too deep

### ISSUE THREAD

**Issue by Thomas-Bibby** [reach-sh/reach-lang#1078]
**Describe the error**

Trying to compile my code works perfectly but then it all of a sudden gave this error. "This error indicates a problem with the Reach compiler, not your program. Please report this error, along with the pertinent program, to the Reach team as soon as possible so we can fix it."

**To Reproduce**

Try to compile my code which is in the zip file.

**Expected behavior**

It is meant to compile like normal with no errors

**Extra information**

latest version of reach which is 0.1.10-rc.6
[index.zip](https://github.com/reach-sh/reach-lang/files/8810945/index.zip)

**Comment by jeapostrophe** [comment]
I'll investigate this. Sorry for the delay!

**Comment by DanBurton** [comment]
If you only care about running this on Algorand, you can specify `setOptions({connectors: [ALGO]})` to work around the issue.

https://docs.reach.sh/rsh/appinit/#setoptions
