### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by joshuafvr** [reach-sh/reach-lang#1164]
![Screenshot_20220617-212122_Termux](https://user-images.githubusercontent.com/74902842/174396595-987417a4-1e2f-4f16-a307-59a272d7ab3c.jpg)
What does this means?

**Comment by jeapostrophe** [comment]
I have no idea :) What do you think it has to do with Reach? :P

**Comment by joshuafvr** [comment]
Same here don't know what it means

**Comment by jeapostrophe** [comment]
Where did it come from? How did you find this repo to report it?

**Comment by joshuafvr** [comment]
I just opened my termux and found those
