### ISSUE TITLE
Reach new api syntax error

### ISSUE THREAD

**Issue by Hikmo** [reach-sh/reach-lang#1194]
I have an application which is written in the new reach api syntax (api_) which you can find in the attach file. While the same code with the old api syntax works without errors the code with new api syntax gives runtime error. Although it compiles without errors it gives runtime error when a call is made to restartSale api. The error is not because of check assertions, however the error itself is not self-explanatory.

The error message:
```Error: UserA.restartSale errored with Error: API call failed: {
  "type": "signAndPost",
  "e": {
    "original": null,
    "response": {
      "message": "TransactionPool.Remember: transaction ZCSEQBC4XHA3MVBKQANTD4JHO4FG3YNTIWOHFRFCPPCALEB76I3A: logic eval error: assert failed pc=1503. Details: pc=1503, opcodes=intc_0 // 0\n==\nassert\n"
    },
    "status": 400
  },
  "es": "Error: Network request error. Received status 400: TransactionPool.Remember: transaction ZCSEQBC4XHA3MVBKQANTD4JHO4FG3YNTIWOHFRFCPPCALEB76I3A: logic eval error: assert failed pc=1503. Details: pc=1503, opcodes=intc_0 // 0\n==\nassert\n" ```

Both the working and failing codes are attached. (The only difference is the api syntax)
[failing.txt](https://github.com/reach-sh/reach-lang/files/8980294/failing.txt)
[working.txt](https://github.com/reach-sh/reach-lang/files/8980295/working.txt)

**Comment by jeapostrophe** [comment]
What function are you calling? What does the calling code look like? `assert` in TEAL *is* `check` in Reach, so it could be that the error is one of the checks. But we'll look at those two questions first.

**Comment by Hikmo** [comment]
You should first deploy the contract with the required params, and then with another account you should trigger the buy function, getting the ownership of the asa. After that if you try to call the restartSale it will give the error I have mentioned above.

**Comment by Hikmo** [comment]
To be more explicit,
```await reach.lib.withDisconnect(() =>
      ctcDeployer.p.Deployer({
        getNFTParams: async (currentTime: any) => {
          const sDeadline =
            saleType == 0 ? convertHoursToBlock(parseFloat(deadline)) : 1;
          return {
            initialPrice: reach.lib.parseCurrency(price),
            royaltyPerc: parseFloat(selectedRow.royalty),
            platformCommission: 2 * 100,
            saleType: saleType,
            sDeadline,
            platform: "ENQY47MBYVVOEFE32SNL6BV75H2Y3CMTFLYGJQ5VFNU3GKKVAFDPIMHZSI",
            claimablesArr: selectedRow.claimablesArr,
            tokenID: tokenId,
          };
        },
        logContract: async (contract: any) => {
          console.log(contract);
        },
        exitFrontend: async () => {
          console.log("exiting");
          reach.lib.disconnect(null);
        },
      }),
    );
```
this is the code I use for deploying the contract where saleType is 1, selectedRow.royalty is 1000, price is 1, tokenID is and id of a random asa that the deployer holds and claimablesArr is an array of length 2 which holds the objects of form
```
{
        claimable: 0,
        shareholder: address,
        share: uint less than 10.000
}
```
After this I trigerr buy with the following code
```
await userApi.buy(reach.lib.parseCurrency(buyPrice));
```
where buyPrice is 1
and after that if I try to call restartSale with the following code:
```
await userApi.restartSale(
          reach.lib.parseCurrency(price),
          convertHoursToBlock(parseFloat(duration)),
          sType,
        );
```
where price and duration are random uints and the saleType is either 0 or 1 I get the error

**Comment by jeapostrophe** [comment]
Can you post your code as a gist so that I can easily read it?

**Comment by jeapostrophe** [comment]
If you don't want to share publicly, you can email or DM me on Discord

**Comment by Hikmo** [comment]
I guess you didn’t have time to accept the invitation but all the code I have is on GitHub issue page

**Comment by jeapostrophe** [comment]
I did not see the invitation on Discord, but I believe that we're talking about this now on the Google Doc. I'm going to close this issue and we'll track things over there.
