### ISSUE TITLE
Reach verifier not working correctly

### ISSUE THREAD

**Issue by Hikmo** [reach-sh/reach-lang#1195]
Even though I ensure some conditions with checks which I will describe further, reach verifier gives errors using examples that are not complying to the check constraints

I have attached the code and the error message is below.
Even though it makes sure that each share should be less than 10.000 with the following code:

  ```require(royaltyArr.all(x => x.share <= TOTAL_SHARE));```

where total share is equal to 10.000

verifier gives the following as an example:

```  //    ^ could = array(Object({"claimable": UInt, "share": UInt, "stakeholder": Address}), [{claimable: 115792089237316195423570985008687907853269984665640564039457584007913129629935, share: 10002, ```

which is impossible.

The code is attached below.
[auto-claim.txt](https://github.com/reach-sh/reach-lang/files/8980410/auto-claim.txt)

**Comment by jeapostrophe** [comment]
The only thing that is known inside of `while` loops (like `parallelReduce`) about loop variables (like `royalties`) is what is in the `invariant`. You should put the claim about their total share in the invariant.

**Comment by Hikmo** [comment]
To be more explicit,
```await reach.lib.withDisconnect(() =>
      ctcDeployer.p.Deployer({
        getNFTParams: async (currentTime: any) => {
          const sDeadline =
            saleType == 0 ? convertHoursToBlock(parseFloat(deadline)) : 1;
          return {
            initialPrice: reach.lib.parseCurrency(price),
            royaltyPerc: parseFloat(selectedRow.royalty),
            platformCommission: 2 * 100,
            saleType: saleType,
            sDeadline,
            platform: "ENQY47MBYVVOEFE32SNL6BV75H2Y3CMTFLYGJQ5VFNU3GKKVAFDPIMHZSI",
            claimablesArr: selectedRow.claimablesArr,
            tokenID: tokenId,
          };
        },
        logContract: async (contract: any) => {
          console.log(contract);
        },
        exitFrontend: async () => {
          console.log("exiting");
          reach.lib.disconnect(null);
        },
      }),
    );```
this is the code I use for deploying the contract where saleType is 1, selectedRow.royalty is 1000, price is 1, tokenID is and id of a random asa that the deployer holds and claimablesArr is an array of length 2 which holds the objects of form
```{
        claimable: 0,
        shareholder: address,
        share: uint less than 10.000
}```
After this I trigerr buy with the following code
```await userApi.buy(reach.lib.parseCurrency(buyPrice));```
where buyPrice is 1
and after that if I try to call restartSale with the following code:
```await userApi.restartSale(
          reach.lib.parseCurrency(price),
          convertHoursToBlock(parseFloat(duration)),
          sType,
        );```
where price and duration are random uints and the saleType is either 0 or 1 I get the error
