### ISSUE TITLE
Not getting token balance by using stdlib function acc.balancesOf Or stdlib.balancesOf

### ISSUE THREAD

**Issue by meetthosar** [reach-sh/reach-lang#1270]
I am trying to get token balance of account using balanceof function but they are not working.

I tried using 

acc.balancesOf(tokens: Array<Token | null>) => Promise<Array<BigNumber>>

And 
stdlib.balancesOf(acc: Account, tokens: Array<Token | null>) => Promise<Array<BigNumber>>

But I am getting `e.eq not a function error`.

You can check code in https://github.com/meetthosar/grab-a-deal/blob/main/src/Components/GrabDeal.js

**Comment by jeapostrophe** [comment]
If you are referring to https://github.com/meetthosar/grab-a-deal/blame/main/src/Components/GrabDeal.js#L68, then are you sure that `account` and `tokenId` have the values you think they do?

**Comment by meetthosar** [comment]
Yes, account and tokenId have values
<img width="1440" alt="Screenshot 2022-07-21 at 3 15 46 PM" src="https://user-images.githubusercontent.com/13599340/180184394-6673e431-ee89-4de6-bbdd-ff62ceec9f56.png">
.

**Comment by meetthosar** [comment]
In Wallet , it shows balance for same token: 
<img width="1118" alt="Screenshot 2022-07-21 at 3 25 49 PM" src="https://user-images.githubusercontent.com/13599340/180186438-cd97d9cd-73aa-495d-9d88-f8fc7148f523.png">

**Comment by jeapostrophe** [comment]
Thank you, I will look into it and get back to you!

**Comment by jeapostrophe** [comment]
I am pushing a fix for this shortly, I apologize for the problem. It will be released on Thursday. In the meantime, if you convert your token value to a BigNumber with `stdlib.bigNumberify` it should work correctly

**Comment by meetthosar** [comment]
No Problem! Thanks a lot! I will try stdlib.bigNumberify.

Thanks once again!
