### ISSUE TITLE
[Bug] Error with Views and Map using Bytes

### ISSUE THREAD

**Issue by Michele971** [reach-sh/reach-lang#1275]
## Purpose
Allow a user to read a value from the map, passing the **key** as parameter when calling the view from frontend.

## Problem definition
I'm trying to set key type to map, different from the default type "address", using Bytes(128).
I'm also trying to retrieve the value (UInt) associated with the key (Bytes(128)).

When the user tried to read the value through the view, the result is ['none', null] although the value is inside the map.

## Tests
I have verified that the values is stored inside the map, it exists! However the view return null.
**If you try to set the key of the map to Address or UInt type, it works.** But not with Bytes(128).

## Backend Code
```
//view definition
const views = View('views', { 
   retrieve_results2: Fun([Bytes(128)], UInt), // View that let Verifier checks the retrieve data
});

 [...]

const easy_map2 = new Map(Bytes(128), UInt);
easy_map2[id_key] = 9999;  //setting the value to a specific key which is publish from Creator participant
views.retrieve_results2.set((m) => fromSome(easy_map2[m], 0)); //the default value is 0
```

## Frontend Code
```
var id_key = await ask.ask(
  `Enter the id_key which you are looking for?`,
  (id_key => id_key)
);
const retrieve_Data2 = await ctc.v.views.retrieve_results2(id_key); 
console.log("retrieve data: ",retrieve_Data2) // this returns Null
```

Thank you in advance!

**Comment by jeapostrophe** [comment]
Does the debugging log return anything interesting?

**Comment by Michele971** [comment]
Nope, nothing special

**Comment by jeapostrophe** [comment]
Can you send me the whole program or the debugging log?

**Comment by Michele971** [comment]
of course!

**Comment by jeapostrophe** [comment]
Thank you!

**Comment by jeapostrophe** [comment]
This was fixed and it will be released on Thursday

**Comment by Michele971** [comment]
> This was fixed and it will be released on Thursday

Thank you
