### ISSUE TITLE
[BUG] Validator doesn't understand that `this` can be a particular address

### ISSUE THREAD

**Issue by MetaB0y** [reach-sh/reach-lang#1297]
I have `beneficiary: Address`, which is `publish`ed by one of the participants.

I have a map and a getter:
```
  const stakedM = new Map(UInt);
  const staked = (p) => fromSome(stakedM[p], 0);
```

And `parallelReduce` with invariant: `staked(beneficiary) == 0`

Now, if I do something like `stakedM[this] = 10` in my `.api`, the invariant is not violated (but it should be).

It doesn't help if I add `check(this === beneficiary)` or even `enforce(addressEq(this, beneficiary))` before.

Latest Reach.

**Comment by jeapostrophe** [comment]
Thank you for finding this problem! I just pushed a fix
