### ISSUE TITLE
Payment and transfer issue within loops

### ISSUE THREAD

**Issue by Jace254** [reach-sh/reach-lang#1298]
### Discussed in https://github.com/reach-sh/reach-lang/discussions/1295

<div type='discussions-op-text'>

<sup>Originally posted by **Jace254** July 26, 2022</sup>
![Capture](https://user-images.githubusercontent.com/47209391/181099929-ade85bf8-cf66-4cd9-bd91-225d8743dc62.PNG)

I get this error when I try paying in portions within a parallel reduce. 
Here is the Repo :
[https://github.com/Jace254/MapsandSets/tree/5515e72b7c11a1790b96a985a1d042eed48bfcab](url)

Is this supposed to happen?

Edit: I added a check to ascertain that the balance is greater than or equal to the payment amount at compilation time but this time it resulted to an error with the compiler

current commit here:

[https://github.com/Jace254/MapsandSets/tree/payment-issue](url)
![Payment  Issue](https://user-images.githubusercontent.com/47209391/181196289-8be8fb13-d450-4da6-8b56-3087b6a4a430.PNG)
</div>

**Comment by jeapostrophe** [comment]
Your `invariant`s (e.g. line 82) doesn't say anything about `balance(JSH)`, so there's no way to ensure that the `transfer` is safe. I'd also remove lines 96 and 97.
