### ISSUE TITLE
Tutorial 8 does not run on Algorand test image

### ISSUE THREAD

**Issue by felipemullen** [reach-sh/reach-lang#142]
At first I thought I had made a mistake when following the tutorial found at https://docs.reach.sh/tut-8.html but it appears there may be something going on in the image.

Steps to reproduce:
- copy `package.json`, `Makefile`, `index.rsh`, `index.mjs`, `docker-compose.yml`, `Dockerfile` into a directory
- move `&default-app` from `reach-app-tut-8-ETH-test-dockerized-geth` to `reach-app-tut-8-ALGO-test-dockerized-algod`
- run `./reach compile`
- run `make build`
- run `make run-alice`

Output is as follows:

```bash
MacBook-Pro-6:tut $ make run-alice
docker-compose run --rm alice
Starting tut_algorand-postgres-db_1 ... done
Starting tut_algorand-devnet_1      ... done

> @reach-sh/tut-8@ index /app
> node --experimental-modules --unhandled-rejections=strict index.mjs

(node:18) ExperimentalWarning: The ESM module loader is experimental.
Are you Alice?
y
Starting Rock, Paper, Scissors! as Alice
Would you like to create an account? (only possible on devnet)
y
Do you want to deploy the contract? (y/n)
y
/stdlib/node_modules/algosdk/src/transaction.js:181
      throw Error(
            ^

Error: Application global byte slices count must be a positive number and smaller than 2^53-1
    at new Transaction (/stdlib/node_modules/algosdk/src/transaction.js:181:13)
    at Object.makeApplicationCreateTxn (/stdlib/node_modules/algosdk/src/makeTxn.js:930:10)
    at deployP (file:///stdlib/ALGO.mjs:975:86)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @reach-sh/tut-8@ index: `node --experimental-modules --unhandled-rejections=strict index.mjs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @reach-sh/tut-8@ index script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I tried to find some information about what is happening but I don't know much about Algorand at this point. The best I could do was this PyTeal Docs page, explaining the `global_num_byte_slices` enum which matches the error message https://pyteal.readthedocs.io/en/latest/api.html#pyteal.TxnField.global_num_byte_slices

**Comment by jeapostrophe** [comment]
Thanks!

If you were doing this in the Reach repository, then it was a fluke because I changed the compilation output but didn't update the compiled version in the repo.

If you were doing it on your own, then perhaps it was a similar problem of having a mismatch between your compiler and runtime images.
