### ISSUE TITLE
While creating ASA in algorand using stdlib.launchToken(), opts.metaDataHash value is ignored and not set in the asset.

### ISSUE THREAD

**Issue by KodisBabu** [reach-sh/reach-lang#1439]
**Describe the error**

While creating ASA in algorand using stdlib.launchToken(), opts.metaDataHash value is ignored and not set in the asset.

opts.metaDataHash value is not set while creating the asset in algorand network

**To Reproduce**
 const nft = await stdlib.launchToken(accLender, "Gold Pass", "GP",{metadataHash: "12345678901234567890123456789012",url:"ipfs://xss.zzz",clawback:accLender.getAddress(),decimals:0,defaultFrozen:false,freeze:accLender.getAddress(),note:JsonToArray(metaData),reserve:accLender.getAddress(),supply:1});

**Expected behavior**

metaDataHash value should have been set

**Extra information**

What version of Reach are you using? You can run `reach version` or `reach hashes` to find out.

**Comment by KodisBabu** [comment]
Actually, i am passing metadataHash as key and it is not set, when i check
in algoexplorer.

-Kodis

**Comment by jeapostrophe** [comment]
Ok. Thank you. I'll schedule someone to debug and get a stable test case for this

**Comment by jeapostrophe** [comment]
Hi @KodisBabu , as #1487 demonstrates, this has always worked if you look at the right field names
