### ISSUE TITLE
Feature Request:  Add manager address in opts for stdlib.launchToken() for Alogrand network

### ISSUE THREAD

**Issue by KodisBabu** [reach-sh/reach-lang#1440]
**Describe the error**

Currently manager address in opts object in stdlib.launchToken() is not supported,  please add manager address in opts for stdlib.launchToken() for Alogrand network.

**To Reproduce**
Try creating with manager field in opts in stdlib.launchToken() and see, it will be ignored.

**Expected behavior**

Manager address should be set, which is the key address in algorand asset.

**Extra information**

What version of Reach are you using? You can run `reach version` or `reach hashes` to find out.

**Comment by jeapostrophe** [comment]
This was added in the last release.
