### ISSUE TITLE
WalletConnect producing undefined importKey error

### ISSUE THREAD

**Issue by cyleecode** [reach-sh/reach-lang#1454]
**Describe the error**
```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'importKey')
Call Stack
W
node_modules/@reach-sh/stdlib/dist/browser/reachsdk.min.js (2:211915)
eval
node_modules/@reach-sh/stdlib/dist/browser/reachsdk.min.js (2:212699)
eval
node_modules/@reach-sh/stdlib/dist/browser/reachsdk.min.js (2:212804)
Module.J
node_modules/@reach-sh/stdlib/dist/browser/reachsdk.min.js (2:212812)
async Q._encrypt
node_modules/@reach-sh/stdlib/dist/browser/reachsdk.min.js (2:232174)
async Q._sendRequest
node_modules/@reach-sh/stdlib/dist/browser/reachsdk.min.js (2:226322)

```

WalletConnect producing error behind the QR and not able to connect.
![error](https://user-images.githubusercontent.com/25987834/194387396-96a0ced3-4627-4c7c-856a-777c811c1c60.jpg)
![error2](https://user-images.githubusercontent.com/25987834/194387418-c654d9a7-221b-4810-a0f4-60d0a4e4b5d2.jpg)

Try to ignore error and scan QR using Pera Wallet gives no response from dapp

**To Reproduce**
Using:
Windows 11
WSL2 - Ubuntu 20.04.5 LTS
"@reach-sh/stdlib": "^0.1.11-rc.9"

**Expected behavior**

Produce no error, wallet should receive signature to sign

**Extra information**

> ./reach version
reach 0.1.12

> ./reach hashes
reach-cli: 4ca32459
reach: 4ca32459
react-runner: 4ca32459
rpc-server: 4ca32459
runner: 4ca32459
devnet-algo: 4ca32459

**Comment by cyleecode** [comment]
Found the actual issue. The underlying stack using web crypto api which require https to work properly, same issue with
https://stackoverflow.com/questions/68479744/cannot-read-property-importkey-of-undefined-web-crypto-api-without-ssl
Problem was solved with setting up https for localhost.

**Comment by jeapostrophe** [comment]
I'm glad you figured it out!
