### ISSUE TITLE
Feature Request: Use algod for asset information if reading is allowed.

### ISSUE THREAD

**Issue by guanzo** [reach-sh/reach-lang#1460]
Similar to how https://github.com/reach-sh/reach-lang/blob/15656b7123fe69ad71d284218a77a3969f13f03f/js/stdlib/ts/ALGO.ts#L1292-L1298 and https://github.com/reach-sh/reach-lang/blob/15656b7123fe69ad71d284218a77a3969f13f03f/js/stdlib/ts/ALGO.ts#L1343-L1349 work, 

`getAssetInfo` should check if the node can read, and if so, fetch asset info from the node instead of the indexer.

**Comment by jeapostrophe** [comment]
Thank you for the request! This issue will be updated when we do it!

**Comment by jeapostrophe** [comment]
This was added in the last release.
