### ISSUE TITLE
launchToken does not set manager address in Algorand TestNet

### ISSUE THREAD

**Issue by giggioz** [reach-sh/reach-lang#1493]
**Describe the error**

using launchToken in ALGORAND TestNet does not set the manager address

**To Reproduce**

I call this function from my react client

```
const createNFT = async () => {
    console.log('CREATING NFT', address);

    const accOpts = {
      clawback: address,
      freeze: address,
      reserve: address,
      manager: address,
    };

    try {
      const theNFT = await reach.launchToken(account, 'AlgoTree', 'NFTree', {
        supply: 1,
        decimals: 0,
        ...accOpts,
      });
      const nftId = theNFT.id;
      console.log('NFT CREATED: NFTid ', reach.bigNumberToNumber(nftId));
    } catch (e) {
      console.log(e);
    }
  };
```

**Expected behavior**

I obtain the NFTId but If I look into it in the explorer all the addresses but the manager are set.

For example
https://testnet.algoexplorer.io/asset/119136364

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/6266740/198414741-6c352b00-4577-4815-bc4b-8942b71844c3.png">

Using

"@reach-sh/stdlib": "0.1.12-rc.6",

**Comment by willghatch** [comment]
Support for the manager field was just added, it's in [0.1.12-rc.7](https://docs.reach.sh/changelog/#guide-changelog).  IE you're one release too early.  But it should work once you have the new version.  (Though I think rc7 hasn't actually been released yet... if it hasn't it will be pretty soon.)

**Comment by giggioz** [comment]
Thank you.
