### ISSUE TITLE
Docs: Reach init adds // ... to default index.rsh script

### ISSUE THREAD

**Issue by BebeGene** [reach-sh/reach-lang#150]
Description
- Confusing use of ellipses in the index.rsh file.

Page Link
- NA, this is not reflected in our documentation, but it appears in the actual index.rsh script.

Search String
- " // ..."

Issue
- When we spin up a new script using ./reach init, it automatically adds "// ..." in it on Line 6. This was very confusing to me in the beginning b/c "..." is actually used in Javascript as a rest operator so it makes me think I missed a critical step. It is not needed here. According to Matt Audesse, "// ..." is intended to be read as "yada yada yada, so on and so forth".
<img width="724" alt="::  issue" src="https://user-images.githubusercontent.com/19564137/119410169-45b04780-bc9d-11eb-87e0-bc07126e7241.png">

Suggestion
- I think remove the ellipses and add an actual sentence instead.

**Comment by chrisnevers** [comment]
Thanks, I've updated the `reach init` code to be more explicit:

```javascript
'reach 0.1';

export const main = Reach.App(() => {
  const Alice = Participant('Alice', {});
  const Bob   = Participant('Bob', {});
  deploy();
  // write your program here

});

```
