### ISSUE TITLE
Doc: 5.4.6.1.7 parallelReduce explanation and parameters definations

### ISSUE THREAD

**Issue by miaoye26** [reach-sh/reach-lang#155]
### Page Link

https://docs.reach.sh/ref-programs-consensus.html#%28reach._%28%28parallel.Reduce%29%29%29

### Search String

5.4.6.1.7 parallelReduce section

### Issue

1) Looking for a High-level explanation and some definition of the parameters for

'ParalleReduce([ true, Funder, 0 ])'

2) Click on .Case brings you to https://docs.reach.sh/ref-programs-compute.html#%28reach._%28%28case%29%29%29
which does not look relevant in this use case

### Suggestion

1) High-level explanation and some definition or examples setting parameters for

'ParalleReduce([ true, Funder, 0 ])' 
2) Some explaination of how function .Case() works and expecting which parameters as inputs

**Comment by hagenhaus** [comment]
I agree. I will look into this. Thx for submitting this issue with the "Doc:" prefix!
