### ISSUE TITLE
Unable to import stdlib in Vite

### ISSUE THREAD

**Issue by Gungy2** [reach-sh/reach-lang#1560]
**Describe the error**

If I try importing anything from `@reach-sh/stdlib` in a Vite browser project, I get the following error: 
```
ReferenceError: process is not defined
    at node_modules/util/util.js (util.js:109:1)
    at __require2 (chunk-JZQ37OGZ.js?v=63656b75:18:50)
    at shared_impl.ts:12:18
```
`stdlib` appears to be using the Node API, which should not be the case, since it is meant to be run on clients.

**To Reproduce**

Import `stdlib` from Vite in the browser.

**Expected behavior**

I expect to get no errors.

**Extra information**

I am using version 0.1.13 of Reach.
Thanks for the help!:)

**Comment by jeapostrophe** [comment]
You should set up your vite to use fallbacks, like this:

https://github.com/reach-sh/reach-lang/blob/master/js/stdlib/webpack.config.js#L20-L26
