### ISSUE TITLE
Error on Remote Solidity Smart Contract

### ISSUE THREAD

**Issue by KBryan** [reach-sh/reach-lang#160]
I had released a bug report on this. It was fixed and now the issue has returned. 

{"contracts":{"index.sol:DaiToken":{"abi":"[{\"inputs\":[],\"stateMutability\":\"nonpayable\",\"type\":\"constructor\"},{\"anonymous\":false,\"inputs\":[{\"indexed\":true,\"internalType\":\"address\",\"name\":\"_owner\",\"type\":\"address\"},{\"indexed\":true,\"internalType\":\"address\",\"name\":\"_spender\",\"type\":\"address\"},{\"indexed\":false,\"internalType\":\"uint256\",\"name\":\"_value\",\"type\":\"uint256\"}],\"name\":\"Approval\",\"type\":\"event\"},{\"anonymous\":false,\"inputs\":[{\"indexed\":true,\"internalType\":\"address\",\"name\":\"_from\",\"type\":\"address\"},{\"indexed\":true,\"internalType\":\"address\",\"name\":\"_to\",\"type\":\"address\"},{\"indexed\":false,\"internalType\":\"uint256\",\"name\":\"_value\",\"type\":\"uint256\"}],\"name\":\"Transfer\",\"type\":\"event\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"_owner\",\"type\":\"address\"},{\"internalType\":\"address\",\"name\":\"_spender\",\"type\":\"address\"}],\"name\":\"allowance\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"remaining\",\"type\":\"uint256\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"\",\"type\":\"address\"},{\"internalType\":\"address\",\"name\":\"\",\"type\":\"address\"}],\"name\":\"allowed\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"_spender\",\"type\":\"address\"},{\"internalType\":\"uint256\",\"name\":\"_value\",\"type\":\"uint256\"}],\"name\":\"approve\",\"outputs\":[{\"internalType\":\"bool\",\"name\":\"success\",\"type\":\"bool\"}],\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"_owner\",\"type\":\"address\"}],\"name\":\"balanceOf\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"\",\"type\":\"address\"}],\"name\":\"balances\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[],\"name\":\"decimals\",\"outputs\":[{\"internalType\":\"uint8\",\"name\":\"\",\"type\":\"uint8\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[],\"name\":\"name\",\"outputs\":[{\"internalType\":\"string\",\"name\":\"\",\"type\":\"string\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[],\"name\":\"symbol\",\"outputs\":[{\"internalType\":\"string\",\"name\":\"\",\"type\":\"string\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[],\"name\":\"totalSupply\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[],\"name\":\"totalSupply_\",\"outputs\":[{\"internalType\":\"uint256\",\"name\":\"\",\"type\":\"uint256\"}],\"stateMutability\":\"view\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"_to\",\"type\":\"address\"},{\"internalType\":\"uint256\",\"name\":\"_value\",\"type\":\"uint256\"}],\"name\":\"transfer\",\"outputs\":[{\"internalType\":\"bool\",\"name\":\"success\",\"type\":\"bool\"}],\"stateMutability\":\"nonpayable\",\"type\":\"function\"},{\"inputs\":[{\"internalType\":\"address\",\"name\":\"_from\",\"type\":\"address\"},{\"internalType\":\"address\",\"name\":\"_to\",\"type\":\"address\"},{\"internalType\":\"uint256\",\"name\":\"_value\",\"type\":\"uint256\"}],\"name\":\"transferFrom\",\"outputs\":[{\"internalType\":\"bool\",\"name\":\"success\",\"type\":\"bool\"}],\"stateMutability\":\"nonpayable\",\"type\":\"function\"}]","bin":"60c0604052600e60808190526d26b7b1b5902220a4902a37b5b2b760911b60a090815261002f916000919061009c565b50604080518082019091526004808252636d44414960e01b602090920191825261005b9160019161009c565b5069d3c21bcecceda10000006002556003805460ff1916601217905534801561008357600080fd5b506002543360009081526004602052604090205561013d565b828054600181600116156101000203166002900490600052602060002090601f0160209004810192826100d25760008555610118565b82601f106100eb57805160ff1916838001178555610118565b82800160010185558215610118579182015b828111156101185782518255916020019190600101906100fd565b50610124929150610128565b5090565b5b808211156101245760008155600101610129565b61063f8061014c6000396000f3fe608060405234801561001057600080fd5b50600436106100b45760003560e01c8063324536eb11610071578063324536eb1461020a5780635c6581651461021257806370a082311461024057806395d89b4114610266578063a9059cbb1461026e578063dd62ed3e1461029a576100b4565b806306fdde03146100b9578063095ea7b31461013657806318160ddd1461017657806323b872dd1461019057806327e235e3146101c6578063313ce567146101ec575b600080fd5b6100c16102c8565b6040805160208082528351818301528351919283929083019185019080838360005b838110156100fb5781810151838201526020016100e3565b50505050905090810190601f1680156101285780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b6101626004803603604081101561014c57600080fd5b506001600160a01b038135169060200135610356565b604080519115158252519081900360200190f35b61017e6103bc565b60408051918252519081900360200190f35b610162600480360360608110156101a657600080fd5b506001600160a01b038135811691602081013590911690604001356103c2565b61017e600480360360208110156101dc57600080fd5b50356001600160a01b03166104a1565b6101f46104b3565b6040805160ff9092168252519081900360200190f35b61017e6104bc565b61017e6004803603604081101561022857600080fd5b506001600160a01b03813581169160200135166104c2565b61017e6004803603602081101561025657600080fd5b50356001600160a01b03166104df565b6100c16104fa565b6101626004803603604081101561028457600080fd5b506001600160a01b038135169060200135610554565b61017e600480360360408110156102b057600080fd5b506001600160a01b03813581169160200135166105de565b6000805460408051602060026001851615610100026000190190941693909304601f8101849004840282018401909252818152929183018282801561034e5780601f106103235761010080835404028352916020019161034e565b820191906000526020600020905b81548152906001019060200180831161033157829003601f168201915b505050505081565b3360008181526005602090815260408083206001600160a01b038716808552908352818420869055815186815291519394909390927f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925928290030190a350600192915050565b60025490565b6001600160a01b0383166000908152600460205260408120548211156103e757600080fd5b6001600160a01b038416600090815260056020908152604080832033845290915290205482111561041757600080fd5b6001600160a01b0380851660008181526004602090815260408083208054889003905593871680835284832080548801905583835260058252848320338452825291849020805487900390558351868152935191937fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef929081900390910190a35060019392505050565b60046020526000908152604090205481565b60035460ff1681565b60025481565b600560209081526000928352604080842090915290825290205481565b6001600160a01b031660009081526004602052604090205490565b60018054604080516020600284861615610100026000190190941693909304601f8101849004840282018401909252818152929183018282801561034e5780601f106103235761010080835404028352916020019161034e565b3360009081526004602052604081205482111561057057600080fd5b336000818152600460209081526040808320805487900390556001600160a01b03871680845292819020805487019055805186815290519293927fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef929181900390910190a350600192915050565b6001600160a01b0391821660009081526005602090815260408083209390941682529190915220549056fea264697066735822122069b843f35deddce2866f47f91b1f8e6f8ae4355079f426093b065fb8146a7b8864736f6c63430007040033"}},"version":"0.7.4+commit.3f05b770.Darwin.appleclang"}file:///app/index.mjs:21  const remoteABI = remoteCtc["abi"];                             ^
TypeError: Cannot read property 'abi' of undefined    at file:///app/index.mjs:21:30

**Comment by jeapostrophe** [comment]
As discussed on Discord, Reach does not provide support for you launching arbitrary smart contracts on the networks we support. You got this code from `examples/remote/index.mjs`, which is a test case for launching a contract and then interacting with. That code relies on the developer knowing how to put things on Ethereum (it uses `ethers` and `solc` directly). I think in most real-world uses, the remote object you want to interact with will already exist.

However, if you want a quick fix, notice in the compiled output from Solidity, the compilation is named `index.sol:DaiToken` rather than `index.sol:WeirdContract` like in the original example. Change the name and it will probably work.

**Comment by KBryan** [comment]
Reach does compile and deploys the smart contract. Set your contract to pragma solidity ^0.7.4; and above is required. Configure your makefile to the desired network if you want to use this approach to launch ERC20 from Reach. You can also modify the frontend to deploy the contracts VIA MetaMask. ¯\_(ツ)_/¯

**Comment by jeapostrophe** [comment]
No, Reach does not compile and deploy the smart contract.

The `examples/remote` directory is an example of a /user/ program that a Reach programmer might write. So, everything inside that directory is *not* Reach, but a program that a Reach programmer happened to write. In other words, it is *you*, not *Reach*.

In that example, the `Makefile`, assumes your computer has `solc` on it and compiles the `index.sol` contract --- https://github.com/reach-sh/reach-lang/blob/master/examples/remote/Makefile#L14-L15 -- that's the compile and *you* did that.

Similarly, the `index.mjs` file, which is written by you, directly requires `ethers` (because *you* know what it is and how to use it) and it deploys the contract --- https://github.com/reach-sh/reach-lang/blob/master/examples/remote/index.mjs#L32 --- that's the deploy and *you* did that too. Just like how in the Rock-Paper-Scissors tutorial, you printed out a message from Bob --- https://github.com/reach-sh/reach-lang/blob/master/examples/tut-7/index.mjs#L49

**Comment by KBryan** [comment]
Okay, I got it to do what I want. Although, it seems that it shouldn't happen or work.

**Comment by jeapostrophe** [comment]
No, it should happen and it should work; it's just that you are attributing it to "Reach", when you should attribute it to "Kwame"; or rather, "Kwame copying Jay's `Makefile` and JavaScript `ethers` code" :P
