### ISSUE TITLE
test

### ISSUE THREAD

**Issue by QL-Sourav-Kumar** [reach-sh/reach-lang#1605]

**Comment by souravql92** [comment]
hi I have made a demo to connect my wallect with the help of "reach" and "txnLab/use-wallet" here is github link [https://github.com/harshQL/reach-demo](url) and here is the demo [https://main--bucolic-flan-da9839.netlify.app/](url) where you can connect your wallet with para wallet and in console you can get your current account  but when i tokenizing my order i m getting an error
