### ISSUE TITLE
FOMO Workshop shouldBuyTicket method

### ISSUE THREAD

**Issue by hagenhaus** [reach-sh/reach-lang#164]
See [index.rsh](https://github.com/reach-sh/reach-lang/blob/master/examples/workshop-fomo/index.rsh).

I believe there is no reason to pass `ticketPrice` to `interact.shouldBuyTicket`. 

`index.mjs` does not use it: `shouldBuyTicket : () => Math.random() < 0.5`

**Comment by jeapostrophe** [comment]
This is an artifact of the automated test. In a real application, the user would want to know the ticket price before agreeing to buy it.
