### ISSUE TITLE
Both branches of ternary opeator is evaluated while using loops

### ISSUE THREAD

**Issue by Zetsuboii** [reach-sh/reach-lang#168]
https://gist.github.com/Zetsuboii/05e473ac22d1ebd176ed8b0b126ecc7a
This is what I've written to produce the error. 

https://gist.github.com/Zetsuboii/3e5792bdfeb3970e5a4eeae4ea856404
This is a similar code without the loop

Without the loop, compiler only evaluates the possible branches.
But when loop is involved  `const temp = i < 5 ? arr[i] : i;`  this line, which normally would work fine because arr has the length of 5, gives array out of bounds error.

**Comment by jeapostrophe** [comment]
This is fixed by a recent change.
