### ISSUE TITLE
Docker fails when Reach project is run in folder with UpperCase Letter

### ISSUE THREAD

**Issue by KBryan** [reach-sh/reach-lang#19]
Here is a screen shot
![Screen Shot 2020-11-02 at 10 49 46 AM](https://user-images.githubusercontent.com/681817/97890730-e3412b00-1cfb-11eb-855a-666a55523856.png)

**Comment by DanBurton** [comment]
Thanks for the report! If you do `reach upgrade` or re-download the `reach` script, it should now work correctly in folders with UpperCase Letters.
