### ISSUE TITLE
Timeout in Rock Paper Scissors example

### ISSUE THREAD

**Issue by hkalodner** [reach-sh/reach-lang#2]
When running `make run-all` after downloading the repository, the RPS test appears to have hung. No new output occurred for around a minute and so I terminated the process and reran the `make run-all` script. The second time, RPS ran correctly without any delay around this step.

Below is the segment of the log that occurred before the hang.

> Running game that times out
> 
> Alice initiates a new game.
> Alice publishes parameters of game: wager of 1.5ETH and escrow of 0.15ETH.
> Bob accepts the terms: wager of 1500000000000000000WEI and escrow of 150000000000000000WEI.
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> (local: Alice plays SCISSORS.)
> Alice commits to play with (hidden) hand.

Below is the output from that same segment in the second run which succeeded.

> Alice initiates a new game.
> Alice publishes parameters of game: wager of 1.5ETH and escrow of 0.15ETH.
> Bob accepts the terms: wager of 1500000000000000000WEI and escrow of 150000000000000000WEI.
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> 	Alice takes her sweet time...
> (local: Alice plays PAPER.)
> Alice commits to play with (hidden) hand.
> Alice thinks outcome is Alice quits.
> Bob thinks outcome is Alice quits.
> Observer thinks outcome is Alice quits.
> Done!

**Comment by jeapostrophe** [comment]
Our updated libraries and integration tests don't have this problem anymore.
