### ISSUE TITLE
Error when using Relay 26be,26be,send,m1,false,SEND REPEAT @ 601 x 33 / Also Related to Algorand 

### ISSUE THREAD

**Issue by KBryan** [reach-sh/reach-lang#208]
I'm receiving this error in projects that implement a Relay account. Here's the debug information for an interactive test runner. Using the Relay example

Starting example game as Relay
Would you like to create an account? (only possible on devnet)
y
Do you want to deploy the contract? (y/n)
n
Please paste the contract information:
{"address":"0xC87539117dfE46FEa8366eFaef3c37C1520e4BeF","creation_block":597,"transactionHash":"0xe7972ce74878e5af997396e9fa908a494d067ce14481cbfc124d8a24cbb52e61"}
Relay balance is: 1000
Alice creates a Relay account.
Alice shares it with Bob outside of the network. {"_isSigner":true,"address":"0x26beBf4a1a4688d8764b85D429e70BAD5171c432","provider":{"_isProvider":true,"_events":[],"_emitted":{"block":-2,"t:0x34c10f3768c7e43d32657f40e79151d324fdc22e03f7be32d7a26d6eda315b32":600,"t:0xd6b518f69dcbd3500dc1efa48b8f6780e2dedc91caf50f2d1c320ca96c72d661":601},"formatter":{"formats":{"transaction":{},"transactionRequest":{},"receiptLog":{},"receipt":{},"block":{},"blockWithTransactions":{},"filter":{},"filterLog":{}}},"anyNetwork":false,"_networkPromise":{},"_maxInternalBlockNumber":601,"_lastBlockNumber":-2,"_pollingInterval":500,"_fastQueryDate":1625760988942,"connection":{"url":"http://ethereum-devnet:8545"},"_nextId":74,"_eventLoopCache":{"detectNetwork":null,"eth_chainId":null,"eth_blockNumber":null},"_network":{"chainId":1337,"name":"unknown"},"_internalBlockNumber":{},"_fastBlockNumber":601,"_fastBlockNumberPromise":{}}}
impossible: The message you are trying to send appears to be invalid.
Error: execution reverted
    at getResult (/stdlib/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:128:21)
    at processJsonFunc (/stdlib/node_modules/@ethersproject/web/lib/index.js:309:22)
    at /stdlib/node_modules/@ethersproject/web/lib/index.js:241:46
    at step (/stdlib/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/stdlib/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/stdlib/node_modules/@ethersproject/web/lib/index.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 3,
  data: '0x100960cb0000000000000000000000000000000000000000000000000000000000000008'
}
args:
[
  [ BigNumber { _hex: '0x0255', _isBigNumber: true } ],
  [
    BigNumber { _hex: '0x015af1d78b58c40000', _isBigNumber: true },
    '0x26beBf4a1a4688d8764b85D429e70BAD5171c432'
  ]
]
/stdlib/dist/cjs/ETH_like.js:786
                                            throw Error(dhead + " REPEAT @ " + block_send_attempt + " x " + block_repeat_count);
                                                  ^

Error: 26be,26be,send,m1,false,SEND REPEAT @ 601 x 33
    at Object.<anonymous> (/stdlib/dist/cjs/ETH_like.js:786:51)
    at step (/stdlib/dist/cjs/ETH_like.js:44:23)
    at Object.next (/stdlib/dist/cjs/ETH_like.js:25:53)
    at fulfilled (/stdlib/dist/cjs/ETH_like.js:16:58)
    at runMicrotasks (<anonymous>)

====
This also appears on Algorand here is the test runner debug information.

Please paste the contract information:
{"ApplicationID":2,"creationRound":13,"Deployer":"6J3K2FVIHK2IEXRIJ52JMZHM3J5XDY7NGZUIZP3FXXSG276OGNKFX3JVXI"}
Relay balance is: 1000
Alice creates a Relay account.
Alice shares it with Bob outside of the network. {"addr":"HYBRXGYCFV56TVVFMSDDMVVB36FZB72GVXLCHZ4SDTPPYTIUJOYGKLPZNE","sk":{"0":107,"1":230,"2":121,"3":162,"4":155,"5":30,"6":171,"7":186,"8":175,"9":205,"10":189,"11":57,"12":130,"13":222,"14":139,"15":136,"16":40,"17":97,"18":63,"19":190,"20":164,"21":215,"22":180,"23":213,"24":62,"25":49,"26":28,"27":203,"28":185,"29":40,"30":217,"31":216,"32":62,"33":3,"34":27,"35":155,"36":2,"37":45,"38":123,"39":233,"40":214,"41":165,"42":100,"43":134,"44":54,"45":86,"46":161,"47":223,"48":139,"49":144,"50":255,"51":70,"52":173,"53":214,"54":35,"55":231,"56":146,"57":28,"58":222,"59":252,"60":77,"61":20,"62":75,"63":176}}
/stdlib/dist/cjs/ALGO.js:1461
                                                            throw Error(dhead + " --- ABORT");
                                                                  ^

Error: BRXG: BRXG sendrecv m1 false --- ABORT
    at /stdlib/dist/cjs/ALGO.js:1461:67
    at step (/stdlib/dist/cjs/ALGO.js:66:23)
    at Object.throw (/stdlib/dist/cjs/ALGO.js:47:53)
    at step (/stdlib/dist/cjs/ALGO.js:51:139)
    at Object.throw (/stdlib/dist/cjs/ALGO.js:47:53)
    at rejected (/stdlib/dist/cjs/ALGO.js:39:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by jeapostrophe** [comment]
As the contract already been used?

**Comment by KBryan** [comment]
Here is a project that show's the error I'm describing.
https://github.com/KBryan/relay_interactive_test_runner

**Comment by KBryan** [comment]
I did some edits to the project described and I know getting the following error.
Bob attaches to the contract as the Relay.
Bob joins the application as the Relay.
/stdlib/dist/cjs/ETH_like.js:397
                            throw Error("I should be " + some_addr + ", but am " + address);
                                  ^

Error: I should be 0xE59a8121827eBD9330a51E2bEbA5B9B3CdC51c06, but am 0x3f44F95959977139a7e301CEE7c4Aa2Ca06b7090
    at Object.iam (/stdlib/dist/cjs/ETH_like.js:397:35)

**Comment by KBryan** [comment]
This seems to be on my end and how Promises are being used. Closing this issue.
