### ISSUE TITLE
Error on transaction affecting Algorand  - Ethereum not affected.

### ISSUE THREAD

**Issue by KBryan** [reach-sh/reach-lang#21]
ExperimentalWarning: The ESM module loader is experimental

<img width="928" alt="Screen Shot 2020-11-05 at 2 11 49 PM" src="https://user-images.githubusercontent.com/681817/98285998-530c1b80-1f71-11eb-8674-647981da9f36.png">

**Comment by jeapostrophe** [comment]
Can you please attach (or privately send) the `rsh` and `mjs` file?

**Comment by jeapostrophe** [comment]
Also, FYI, `The ESM module loader is experimental` is not really an error; it's just Node.js telling us that this feature, which has been around for over five years, is "experimental". Actually, the next release of Node.js is supposed to remove the warning. But the other part of the error is definitely real.

**Comment by DanBurton** [comment]
We were not able to reproduce the error. @KBryan mentioned that this issue fixed itself for him. Kindly reopen if it comes up again; thanks!
