### ISSUE TITLE
ParseVal Error With Reach

### ISSUE THREAD

**Issue by jboetticher** [reach-sh/reach-lang#212]
Attempted to make a reach program, but it had a parse issue. 

Here is the error:
```
Verifying knowledge assertions
Verifying for generic connector
  Verifying when ALL participants are honest
Verification failed:
  when ALL participants are honest
  of theorem: while invariant after loop
  at ./index.rsh:118:3:invariant

reachc: The compiler has encountered an internal error:

  parseVal: Array(Object({"date": UInt, "inventoryUnit": UInt, "inventoryValue": UInt, "stateName": UInt, "supplyName": UInt, "transitions": Array(UInt, 10), "transitionsLength": UInt}), 10) List [Atom "_",Atom "as-array",Atom "k!38"]

This error indicates a problem with the Reach compiler, not your program. Please report this error, along with the pertinent program, to the Reach team as soon as possible so we can fix it.

Open an issue at: https://github.com/reach-sh/reach-lang/issues

CallStack (from HasCallStack):
  error, called at src/Reach/Util.hs:73:3 in reach-0.1.2-DAFksisXDyRKXmySyEXCbN:Reach.Util
  impossible, called at src/Reach/Verify/SMT.hs:467:10 in reach-0.1.2-DAFksisXDyRKXmySyEXCbN:Reach.Verify.SMT
```

Here is the gist of the code that generated the issue:
https://gist.github.com/jboetticher/33dffa61b5904a887421ab86dd7f3dd3

**Comment by jboetticher** [comment]
As far as I can tell, this could be an issue with trying to use `Array.replicate` on an object.

**Comment by chrisnevers** [comment]
Hi @jboetticher , thanks for opening this issue. 

I believe you are using an old version of `reach`. Could you run `reach update`, followed by `reach hashes` and ensure you are using the following versions:

```
$ reach hashes
reach: c40c2f5c
ethereum-devnet: c40c2f5c
algorand-devnet: c40c2f5c
devnet-cfx: c40c2f5c
runner: c40c2f5c
react-runner: c40c2f5c
rpc-server: c40c2f5c
```

After updating, you should no longer receive this internal compiler error. However, there is a verification error in your code & I notice that the verification error we provide is rather sub-par. When we display the value of the violation witnesses, `Array`s that are nested in `Object`s are displaying as empty. I will create an internal ticket to fix this issue and provide a better error message.

-Chris

**Comment by jboetticher** [comment]
It looks like I was on reach hash de6bd627. Weird... I followed the installation procedure in the tutorial. Thanks for the help, and hope the updated verification error will help someone else in the future.
