### ISSUE TITLE
Testing suite outside of a network

### ISSUE THREAD

**Issue by Lumene98** [reach-sh/reach-lang#213]
Do you have in program an outside-of-the-network testing suite or something related to testing?

**Comment by jeapostrophe** [comment]
Please correct me if I am wrong. I think you are saying, "All of the Reach examples use automated tests that work with a devnet. Can I write test programs that don't use any network at all, like how I write unit tests in my normal JavaScript code?" If that's the question, then the answer is that you would just write unit tests as `assert`s. This article --- https://docs.reach.sh/guide-assert.html --- and this tutorial section --- https://docs.reach.sh/tut-5.html --- are about that.

**Comment by Lumene98** [comment]
Thanks!
