### ISSUE TITLE
More accurate error handling for lost races on ETH devent

### ISSUE THREAD

**Issue by keeganthomp** [reach-sh/reach-lang#224]
After speaking with Dan, It appears that the following message is not always the result of insufficient funds. Even though the error may be actually be because a user lost a race, the message `insufficient funds for gas * price + value` does not reflect that.

```
WARN [07-21|16:43:59.013] Served eth_sendRawTransaction   conn=172.18.0.1:61222 reqid=8148973790804  t="499.2µs" err="insufficient funds for gas * price + value"
```

From Discord:
>In a reach program, sometimes there are "races" to see who can do the thing first. (parallelReduce introduces races, as well as race, obviously.) Whoever wins the race gets their transaction committed. People who tried to join the race but lost get their transactions reverted. 

It would be helpful to know what is happening or why the the program is failing instead of the generic `insufficient funds for gas * price + value` message. Currently, it is a bit difficult to triage an issue when looking at this error in the stacktrace, as one is led to believe that the error is because of  insufficient funds, but that is not often not the case when this error exist.

From Discord:
>iirc "insufficient funds" isn't always accurate at explaining what the error actually was; I think sometimes there's a library somewhere in the stack that sees a reverted transaction and assumes that the error was insufficient funds, even though the real reason was that the contract rejected the transaction (such as when someone loses a race).

**Comment by jeapostrophe** [comment]
I have never been able to get a more specific error out of the geth (the real Ethereum node), but when you run with Ganache, you get some more accurate. I think that the information you want simply isn't provided to us

**Comment by keeganthomp** [comment]
@jeapostrophe thanks for the prompt reply. I understand. Feel free to close this bad boy.
