### ISSUE TITLE
Send Error: cannot estimate gas;

### ISSUE THREAD

**Issue by cb0806151** [reach-sh/reach-lang#229]
Alright, running into an interesting error when I try REACH_DEBUG=true ./reach run on this Mancala contract. I currently have it set up to test just one move but it throws this in the debug:
```
SEND ERROR Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT"
```
and this when using just plain old ./reach run
```
impossible: The message you are trying to send appears to be invalid.
Error: execution reverted
    at getResult (/stdlib/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:128:21)
    at processJsonFunc (/stdlib/node_modules/@ethersproject/web/lib/index.js:309:22)
    at /stdlib/node_modules/@ethersproject/web/lib/index.js:241:46
    at step (/stdlib/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/stdlib/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/stdlib/node_modules/@ethersproject/web/lib/index.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 3,
  data: '0x4e487b710000000000000000000000000000000000000000000000000000000000000011'
}
```
network type: ETH
contract: https://gist.github.com/cb0806151/4501aa801d4f62026fb6f5424da6cbc0
mjs file: https://gist.github.com/cb0806151/fc6d0ff90649e5ed7db7ce7b4c1e3fb7

I've narrowed it down to that point at the end where its trying to relay the state to the mjs file
```
   B.only(() => {
     interact.relayState(newState);
   });
```
and if its commented out the error goes away and the rest of the contract runs fine, but I need the ability to send the state to the frontend for this application to work

The movePieces function runs fine on its own, but here (from what I can gather) it seems to be creating a different object when inside the executeMove function that can't be passed to the frontend or even comprehended by the contract

**Comment by cb0806151** [comment]
When tested on the Algorand network with `REACH_CONNECTOR_MODE=ALGO ./reach run` it returns a slightly more error
```
/stdlib/dist/cjs/shared_backend.js:33
    throw Error("bigNumberify: " + x + " out of range [0, " + m + "] at " + at);
          ^

Error: bigNumberify: -5 out of range [0, 18446744073709551615] at internal
    at Object.checkedBigNumberify (/stdlib/dist/cjs/shared_backend.js:33:11)
    at check (/stdlib/dist/cjs/shared_impl.js:275:33)
    at Object.sub (/stdlib/dist/cjs/shared_impl.js:278:40)
    at file:///app/build/index.main.mjs:352:27
    at Array.map (<anonymous>)
    at file:///app/build/index.main.mjs:345:23
    at /stdlib/dist/cjs/ALGO.js:1224:62
    at step (/stdlib/dist/cjs/ALGO.js:66:23)
    at Object.next (/stdlib/dist/cjs/ALGO.js:47:53)
    at /stdlib/dist/cjs/ALGO.js:41:71
```

**Comment by jeapostrophe** [comment]
It's hard to find exactly the problem, because I don't understand your computation, but you are using `UInt`, but computing negative numbers. If you turn on `verifyArithmetic: true`, then you'll see some errors related to that. Although @chrisnevers ; there's a ParseVal error that you'll need to fix for the message to be great.

**Comment by cb0806151** [comment]
Ah okay; I'll turn that setting on and see what I can find out. Thanks Jay!
