### ISSUE TITLE
Algorand stateful smart contract: dynamic cost budget of 700 exceeded, executing gtxns 

### ISSUE THREAD

**Issue by Sonlis** [reach-sh/reach-lang#233]
While executing the [tic-tac-toe](https://github.com/reach-sh/reach-lang/blob/master/examples/ttt/index.rsh) example, on the Algorand blockhain, it raises the following error after the 7th move:
``` logic eval error: pc=2260 dynamic cost budget of 700 exceeded, executing gtxns ```
I assume this is due to the smart contract replaying each transaction on each move, while its cost limit is 700. To fix it, I believe storing the state globally or locally, and only playing each transaction once, will fix it.

**Comment by jeapostrophe** [comment]
This is as expected. Not all programs work on Algorand, because it has very strict time and space budgets.
