### ISSUE TITLE
TimeOut Issue with Tutorial 6 and 7

### ISSUE THREAD

**Issue by geokos009** [reach-sh/reach-lang#243]
I am facing this issue in tutorial 2.6 and 2.7. The code runs properly when Bob doesn't take his sweet time. This is what happens when Bob takes his sweet time. 

Only happens when running for ETH network. Algo I didn't face this issue after running it multiple times.

> node --experimental-modules --unhandled-rejections=strict index.mjs

Bob accepts the wager of 5.
Alice played Paper
Bob played Scissors
 Bob takes their sweet time sending it back... 
 Bob takes their sweet time sending it back... 
 Bob takes their sweet time sending it back... 
 Bob takes their sweet time sending it back... 
 Bob takes their sweet time sending it back... 
 Bob takes their sweet time sending it back... 
 Bob takes their sweet time sending it back... 
 Bob takes their sweet time sending it back... 
 Bob takes their sweet time sending it back... 
 Bob takes their sweet time sending it back... 
impossible: The message you are trying to send appears to be invalid.
Error: execution reverted
    at getResult (/stdlib/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:128:21)
    at processJsonFunc (/stdlib/node_modules/@ethersproject/web/lib/index.js:309:22)
    at /stdlib/node_modules/@ethersproject/web/lib/index.js:241:46
    at step (/stdlib/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/stdlib/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/stdlib/node_modules/@ethersproject/web/lib/index.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 3,
  data: '0x100960cb000000000000000000000000000000000000000000000000000000000000001b'
}
args:
[
  [
    '0x66cC6b7e957F9d0B4d7d5459DaE9fF4CcdD43737',
    BigNumber { _hex: '0x4563918244f40000', _isBigNumber: true },
    BigNumber { _hex: '0x0a', _isBigNumber: true },
    '0xf5068DaBaD7a349fBfFb635d66E8f67EA8029417',
    BigNumber {
      _hex: '0x3c229c50fbe2c462e6eb84235734599238cbd704574ee2160c852c047461f0c0',
      _isBigNumber: true
    },
    BigNumber { _hex: '0x43', _isBigNumber: true },
    BigNumber { _hex: '0x8ac7230489e80000', _isBigNumber: true }
  ],
  [ BigNumber { _hex: '0x02', _isBigNumber: true } ]
]
/stdlib/dist/cjs/ETH_like.js:790
                                            throw Error(dhead + " REPEAT @ " + block_send_attempt + " x " + block_repeat_count);
                                                  ^

Error: f506,f506,send,m8,time,67,SEND REPEAT @ 67 x 33
    at Object.<anonymous> (/stdlib/dist/cjs/ETH_like.js:790:51)
    at step (/stdlib/dist/cjs/ETH_like.js:44:23)
    at Object.next (/stdlib/dist/cjs/ETH_like.js:25:53)
    at fulfilled (/stdlib/dist/cjs/ETH_like.js:16:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @reach-sh/tut-index@ index: `node --experimental-modules --unhandled-rejections=strict index.mjs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @reach-sh/tut-index@ index script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-09T05_28_55_862Z-debug.log
ERROR: 1
make[1]: *** [run-target] Error 1
make: *** [run] Error 2

**Comment by jeapostrophe** [comment]
Sorry about this, I pushed a fix this weekend and we did a release with it yesterday that fixed. Can you update (`reach update`) and try again?

**Comment by geokos009** [comment]
> Sorry about this, I pushed a fix this weekend and we did a release with it yesterday that fixed. Can you update (`reach update`) and try again?

**Comment by geokos009** [comment]
Thank you Jay! Appreciate the effort that you and your team have put to dole out some good tutorials.

**Comment by jeapostrophe** [comment]
Thank you for the note and sorry again about the breakage :)
