### ISSUE TITLE
Arrow returns don't work with match

### ISSUE THREAD

**Issue by Zetsuboii** [reach-sh/reach-lang#253]
```js
'reach 0.1';

export const main = Reach.App(() => {
  const Alice = Participant('Alice', {
    // Specify Alice's interact interface here
    log: Fun(true, Null)
  });
  const Bob = Participant('Bob', {
    // Specify Bob's interact interface here
  });
  deploy();
  // write your program here
  Alice.publish();

  const ABData = Data({
    a: UInt,
    b: UInt
  });

  const abInstance = Data.a(5);

  const matchResult = abInstance.match({
    a: (val) => val,
    b: (val) => val
  });

  Alice.interact.log(matchResult);
});
```
This code raises 
```
reachc: Unexpected token, ColonToken at ./index.rsh:24:6
CallStack (from HasCallStack):
  error, called at src/Reach/Parser.hs:274:15 in reach-0.1.3-DZJpvBVK5mFLRGiTzefmMG:Reach.Parser
```
error, and changing match expression to
```js
  const matchResult = abInstance.match({
    a: (val) => { return val },
    b: (val) => { return val }
  });
```
solves it. Would be better if both version worked

**Comment by jeapostrophe** [comment]
This is not a Reach problem. This is just a misunderstanding on your part of what JavaScript syntax is.

The `,` on line 23 --- `val,` is the comma operator and the next expression, on the next line, is an identifier, `b`, and the `:` is not allowed there. On the right-hand side of a `=>` is an expression, and you've written an expression `val, b` (which means, evaluate `val`, throw it way, return `b`).

This is why, if you look at all our examples, we would write this `((val) => val),` to prevent the use of the `,` operator.

**Comment by Zetsuboii** [comment]
Oh, I thought it worked like how objects work in Js as you can define arrow functions inside objects. But I guess it is different than objects.

```js
const obj = {
  a: (val) => val*2,
  b: (val) => val*3
}

console.log( obj.a(2) ); // 4
console.log( obj.b(2) ); // 6
```

I believe same principle goes for parallelReduce, even though it is possible to pass arrow callbacks to functions that calls other functions without comma operator being an issue; we have to pass arrow functions inside parentheses.

```js
function callEverythingWith1 (fn1, fn2, fn3) {
  console.log(fn1(1));
  console.log(fn2(1));
  console.log(fn3(1));
}

callEverythingWith1(
  (x) => x*2,
  (x) => x**2,
  (x) => x/2
)
// 2
// 1
// 0.5
``` <- This probably wouldn't work in Reach

**Comment by jeapostrophe** [comment]
It is possible that this is a limitation of the JS parser we use related to this branch https://github.com/reach-sh/reach-lang/tree/js-concise-body

**Comment by jeapostrophe** [comment]
Nevers implemented this recently and now we get what we want from arrows in arguments.
