### ISSUE TITLE
Reach generated Solidity error when deploying contract using injected Web3 from Remix.

### ISSUE THREAD

**Issue by KBryan** [reach-sh/reach-lang#257]
When running Reach generated Solidity in Remix I received the following error.

This contract may be abstract, not implement an abstract parent's methods completely or not invoke an inherited contract's constructor correctly.

Being convinced this was my end. I tried the Solidity that is found in the tutorial 

https://github.com/reach-sh/reach-lang/blob/master/examples/tut-8/build/index.main.sol 

This is the result when trying to deploy in remix 

![Screen Shot 2021-08-27 at 8 28 39 AM](https://user-images.githubusercontent.com/681817/131128385-ff266de7-6be1-4236-ba92-10b3dd14a16c.png)

**Comment by jeapostrophe** [comment]
I don't think this error is meaningful. The ReachContract doesn't have an abstract parent or anything like that. Is there a way for Remix to give a more specific message?

**Comment by KBryan** [comment]
Here is a gist containing more information. Hope it helps.

https://gist.github.com/KBryan/8f2910833ee4260ac04e17d5c8a7f9eb

**Comment by jeapostrophe** [comment]
Thanks!
