### ISSUE TITLE
Deploy on conflux and got transaction timeout error

### ISSUE THREAD

**Issue by JupiterXiaoxiaoYu** [reach-sh/reach-lang#272]
run DAPP on conflux but got timeout throw while deploying.
![image](https://user-images.githubusercontent.com/71649294/132949387-0c51e2a0-dcf6-4195-a29a-4f3029c49991.png)

here's the code
https://github.com/JupiterXiaoxiaoYu/reach-edcredit

**Comment by jeapostrophe** [comment]
Are you deploying to a devnet? Testnet?

**Comment by JupiterXiaoxiaoYu** [comment]
I'm using Testnet

**Comment by JupiterXiaoxiaoYu** [comment]
> Are you deploying to a devnet? Testnet?

Testnet

**Comment by DanBurton** [comment]
@JupiterXiaoxiaoYu I've updated the docs with more information about deploying to TestNet on Conflux. Can you take a look at this and let us know if these instructions resolve your issue?

https://docs.reach.sh/ref-network-cfx.html#%28part._cfx-faq-mainnet%29

**Comment by jeapostrophe** [comment]
We've just done a release that has ironed out the last kinks in this. Please let us know if you have a similar problem in the future.

**Comment by JupiterXiaoxiaoYu** [comment]
ok thx
