### ISSUE TITLE
Unexpected behavior in Rock, Paper, Scissors with 2 Alice instances

### ISSUE THREAD

**Issue by Thegaram** [reach-sh/reach-lang#277]
I tried the "Rock, Paper, Scissors" by playing 2x Alice and 1x Bob (simultaneously). The game between Alice1 and Bob is normal and Bob wins. However, instead of failing to join the game, Alice2 will also lose regardless of her hand.

Not sure what is going on here or whether this is covered in the docs. If it is not, I suggest you add some remarks about what this situation translates to in a Reach contract.

Alice1:
```
Are you Alice?
y
Starting Rock, Paper, Scissors! as Alice
Would you like to create an account? (only possible on devnet)
y
Do you want to deploy the contract? (y/n)
 
Only y/n are acceptable.
valid answer pls? > 
y
The contract is deployed as = "NET999:TYPE.CONTRACT:ACBM167CXCA8GBRPXU3WWMK6YN0AM6M6FA4RVR9YNV"
Your balance is 997.4374
How much do you want to wager?
1
What hand will you play?
Rock
You played Rock
The outcome is: Bob wins
Your balance is now 998.9999
```

Bob:
```
Are you Alice?
n
Starting Rock, Paper, Scissors! as Bob
Would you like to create an account? (only possible on devnet)
y
Do you want to deploy the contract? (y/n)
n
Please paste the contract information:
"NET999:TYPE.CONTRACT:ACBM167CXCA8GBRPXU3WWMK6YN0AM6M6FA4RVR9YNV"
Your balance is 1000
Do you accept the wager of 1?
y
What hand will you play?
Paper
You played Paper
The outcome is: Bob wins
Your balance is now 1000.9999
```

Alice2
```
Are you Alice?
y
Starting Rock, Paper, Scissors! as Alice
Would you like to create an account? (only possible on devnet)
y
Do you want to deploy the contract? (y/n)
n
Please paste the contract information:
"NET999:TYPE.CONTRACT:ACBM167CXCA8GBRPXU3WWMK6YN0AM6M6FA4RVR9YNV"
Your balance is 1000
How much do you want to wager?
2
What hand will you play?
Paper
You played Paper
The outcome is: Bob wins
Your balance is now 997.9999
```

**Comment by jeapostrophe** [comment]
The second isn't losing, she's just observing the outcome of the game. If you were to have done this in a browser, you would not have seen any signing attempts, because she's just watching the old messages from the first time you played the game. The contract exists for exactly one occurrence of the game and then it is over, but the blockchain records what happened forever and people can always go re-watch it.

**Comment by Thegaram** [comment]
Thanks for the explanation. In this case, I wonder why the final balance of Alice2 is `997.9999`? I'd expect it to be `1000`.

**Comment by jeapostrophe** [comment]
In my experience, it is often the case that client-side libraries (like Ethers) will cache an account's balance and locally update it when they issue transactions. So, if my balance is 100, then I make a txn that costs me 1, the library updates the balance to 99, but when the txn is rejected, the library doesn't actually update the balance automatically and will only lazily (such as after a cache timeout) query the network again for my real balance. I've seen this more obviously in Web versions where the UI is programmed to periodically poll for the balance and it will suddenly flip back to the expected 100.
