### ISSUE TITLE
Backend Error from ./reach run

### ISSUE THREAD

**Issue by jboetticher** [reach-sh/reach-lang#278]
[This is the gist where the error occurs.](https://gist.github.com/jboetticher/3d02bb7af3748d149cf8528da5e5fcc5)
The code is modified from the dumb nft example, which still runs fine.

My reach & eth hash is d2b0c4e5, with everything else 92f35160.

The output when running 'reach run' is:
`
Alice makes id #48383029078477871379525852225787778183581072106774930890024756709128553286536
args:
[
  [ BigNumber { _hex: '0x0f', _isBigNumber: true } ],
  [
    BigNumber {
      _hex: '0x6af7d2f277c0bef9d26e6a6317832bae1d7958cb36072763265e8bb7f156cb88',
      _isBigNumber: true
    }
  ]
]
`
Hamza suggested that I make a GitHub issue, since it is not expected to have a backend related error on runtime.

**Comment by jeapostrophe** [comment]
What's the error?

**Comment by jboetticher** [comment]
Ah, sorry. I thought I included the entire thing in the copy & paste.
```
args:
[
  [ BigNumber { _hex: '0x1d', _isBigNumber: true } ],
  [
    BigNumber {
      _hex: '0x54cd029cf64a07026cb92d0a67d505bc4ae81503e25d4fa8f79dbb5b3619d2c3',
      _isBigNumber: true
    }
  ]
]
/stdlib/dist/cjs/ETH_like.js:888
                                            throw Error(dhead + " REPEAT @ " + block_send_attempt + " x " + block_repeat_count);
                                                  ^

Error: 461F,461F,send,m1,,SEND REPEAT @ 29 x 33
    at Object.<anonymous> (/stdlib/dist/cjs/ETH_like.js:888:51)
    at step (/stdlib/dist/cjs/ETH_like.js:44:23)
    at Object.next (/stdlib/dist/cjs/ETH_like.js:25:53)
    at fulfilled (/stdlib/dist/cjs/ETH_like.js:16:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by jeapostrophe** [comment]
Thank you. I will look at it in more detail. If you want some more context, you can run with `REACH_DEBUG=Y` and you'll get a lot more output.

This error means that the `publish` on this line is being rejected --- https://gist.github.com/jboetticher/3d02bb7af3748d149cf8528da5e5fcc5#file-index-rsh-L57 --- despite the local client being honest.

I can't tell why you aren't seeing any other log messages. But I'll look into it more.

**Comment by jeapostrophe** [comment]
Closing, please reopen if you can find any more detail.
