### ISSUE TITLE
Reach Compiler Issue

### ISSUE THREAD

**Issue by geokos009** [reach-sh/reach-lang#279]
Encountered this error message when compiling :

Verifying knowledge assertions
Verifying for generic connector
  Verifying when ALL participants are honest
reachc: The compiler has encountered an internal error:

  p

This error indicates a problem with the Reach compiler, not your program. Please report this error, along with the pertinent program, to the Reach team as soon as possible so we can fix it.

Open an issue at: https://github.com/reach-sh/reach-lang/issues

CallStack (from HasCallStack):
  error, called at src/Reach/Util.hs:75:3 in reach-0.1.4-2ZKi32JNzIACxBH7cb1Ora:Reach.Util
  impossible, called at src/Reach/Verify/SMT.hs:598:9 in reach-0.1.4-2ZKi32JNzIACxBH7cb1Ora:Reach.Verify.SMT

**Comment by jeapostrophe** [comment]
Can you share the program that leads to this error? If you don't want to post it, you can email me directly or DM me on Discord.

**Comment by AwolDes** [comment]
@geokos009 @jeapostrophe I am also getting something similar to this now. The extra information I can add is that a `z3` command is going bezerk and chewing up CPU. The compile command just hangs until I kill `z3` using htop, then I get this error.

`reachc: user error (Missing response from solver)`

I'm on Ubuntu 18.04, and this started happening only today. It was fine all morning then out of no where compiler problems, even after a restart.

**Comment by jeapostrophe** [comment]
@AwolDes This is a completely unrelated problem. If you want to send me the entire program, I could look into it. I don't have enough context to see why one program would converge but the other would take forever. But basically, what you're experiencing is completely expected from Z3. We spend up to 2 minutes per theorem, so if your program has 100 theorems, it could take up to 200 minutes to finish verifying. Most theorems complete in less than 10ms, so it is rare to have that behavior, but it doesn't indicate anything is wrong.

**Comment by AwolDes** [comment]
@jeapostrophe ok cheers for the explanation. I have another case which causes the same type of behavior, should I just DM on discord?

**Comment by jeapostrophe** [comment]
@AwolDes Yes please!
