### ISSUE TITLE
Reach 0.1 does not work

### ISSUE THREAD

**Issue by vporton** [reach-sh/reach-lang#33]
```
$ ./reach compile
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 125, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 53, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 156, in get_project
    execution_context_labels(config_details, environment_file),
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 163, in execution_context_labels
    '{0}={1}'.format(LABEL_CONFIG_FILES, config_files_label(config_details)),
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 172, in config_files_label
    return ",".join(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 173, in <genexpr>
    map(str, (os.path.normpath(c.filename) for c in config_details.config_files)))
  File "/usr/lib/python3.8/posixpath.py", line 336, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

It's reach from later `master` branch.

**Comment by DanBurton** [comment]
@vporton thanks for the report. Can you give us a little more info about your current setup? These details might help:

* current OS
* the output of `./reach hashes`
* the contents of the file you are trying to compile

**Comment by vporton** [comment]
> @vporton thanks for the report. Can you give us a little more info about your current setup? These details might help:
> 
> * current OS
Ubuntu 20.04.1
> * the output of `./reach hashes`

@DanBurton 
```
reach: 6bce421a
ethereum-devnet: 6bce421a
algorand-devnet: 6bce421a
stdlib: 6bce421a
runner: 6bce421a
react_runner: 6bce421a
```
> * the contents of the file you are trying to compile
```
import {loadStdlib} from '@reach-sh/stdlib';
import * as backend from './build/index.main.mjs';

(async () => {
  const stdlib = await loadStdlib();
  const startingBalance = stdlib.parseCurrency(100);

  const alice = await stdlib.newTestAccount(startingBalance);
  const bob = await stdlib.newTestAccount(startingBalance);

  const ctcAlice = alice.deploy(backend);
  const ctcBob = bob.attach(backend, ctcAlice.getInfo());

  await Promise.all([
    backend.Alice(ctcAlice, {
      ...stdlib.hasRandom
    }),
    backend.Bob(ctcBob, {
      ...stdlib.hasRandom
    }),
  ]);

  console.log('Hello, Alice and Bob!');
})();
```

**Comment by cswenor** [comment]
That looks like the mjs file. Can you please also include your rsh file?

**Comment by DanBurton** [comment]
What @cswenor said. But also. I suspect it might be an issue with the way we are using docker-compose.

Could you paste the output of `docker-compose --version` and `docker --version` ?

You can also try `./reach update` to grab slightly newer containers (`./reach hashes` output will change), but I suspect this will not be sufficient to address the issue.

**Comment by vporton** [comment]
> That looks like the mjs file. Can you please also include your rsh file?

```
'reach 0.1';

export const main = Reach.App(
  {}, [['Alice', {}], ['Bob', {}]], (Alice, Bob) => {
    // ...
  }
);
```

**Comment by vporton** [comment]
> What @cswenor said. But also. I suspect it might be an issue with the way we are using docker-compose.
> 
> Could you paste the output of `docker-compose --version` and `docker --version` ?

```
docker-compose --version
docker-compose version 1.25.0, build unknown
docker --version
Docker version 19.03.14, build 5eb3275d40
```

> You can also try `./reach update` to grab slightly newer containers (`./reach hashes` output will change), but I suspect this will not be sufficient to address the issue.

`./reach update` does not help.

**Comment by DanBurton** [comment]
@vporton thanks for the additional info. Those versions seem reasonable, so I'm still not sure what could be going wrong here, but I still suspect it's an issue with docker-compose.

Have you used `docker-compose` successfully for other projects? Could you try upgrading to docker-compose version `1.27.4`?

**Comment by cswenor** [comment]
@vporton If you would like you can join our Discord channel and we can work on this live with you. https://discord.com/invite/AZsgcXu

**Comment by vporton** [comment]
> Have you used `docker-compose` successfully for other projects? Could you try upgrading to docker-compose version `1.27.4`?

Yes, I did. I can upgrade, but that's not good if your software does not work with the _latest_ version of the most popular free OS (Ubuntu). So, should I upgrade? Or first consult the Discord.

**Comment by DanBurton** [comment]
Okay, I think I found and fixed the issue via 33333e5. @vporton can you run `./reach upgrade` or re-download the `reach` script and try again? I tested it on an Ubuntu 20.04 VM with docker-compose 1.25.0, so it _should_ work.

**Comment by vporton** [comment]
> Okay, I think I found and fixed the issue via [33333e5](https://github.com/reach-sh/reach-lang/commit/33333e5d349111303b5751aeedace842971b914c). @vporton can you run `./reach upgrade` or re-download the `reach` script and try again? I tested it on an Ubuntu 20.04 VM with docker-compose 1.25.0, so it _should_ work.

```
salaries,0$ ./reach upgrade
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24634  100 24634    0     0  50583      0 --:--:-- --:--:-- --:--:-- 50583
salaries,0$ ./reach compile
Verifying knowledge assertions
Verifying for generic connector
  Verifying with mode = VM_Honest
  Verifying with mode = VM_Dishonest RoleContract
  Verifying with mode = VM_Dishonest (RolePart "Alice")
  Verifying with mode = VM_Dishonest (RolePart "Bob")
Checked 4 theorems; No failures!
```

I will mark this issue closed.

However, in some reason:

```
salaries,0$ ./reach run
I'm confused, some scaffolded files exist, but not all
```

**Comment by jeapostrophe** [comment]
Thanks @vporton ! For the `./reach run` error. In the directory, you should see some files with names like `.index` and so on. You can just delete those. I believe that you can also run `./reach unscaffold`. My guess is that they remained from when the `docker-compose` failed part way. Thanks for bearing with us!

**Comment by hamirmahal** [comment]
> ```
> salaries,0$ ./reach run
> I'm confused, some scaffolded files exist, but not all
> ```

For future people reading this, I just want to report that I also encountered the `I'm confused, some scaffolded files exist, but not all` error message, and I resolved it by removing `package.json`, which I myself had added earlier by running `npm i --save-dev @types/node` .
