### ISSUE TITLE
Module not found: Can't resolve 'net'

### ISSUE THREAD

**Issue by 1forh** [reach-sh/reach-lang#339]
Trying to follow along with this tutorial https://developer.algorand.org/tutorials/algorand-blockchain-development-using-reach-part-7-reactjs-front-end-and-algosigner-integration and getting an error. Any help would be appreciated!

**Describe the error**

When using the code in my ts file `import * as reach from '@reach-sh/stdlib/ALGO';` I get the below error: 

```
Module not found: Can't resolve 'net'

Import trace for requested module:
./node_modules/@reach-sh/stdlib/waitPort.mjs
./node_modules/@reach-sh/stdlib/ALGO.mjs
./pages/_app.tsx
```

<img width="437" alt="CleanShot 2021-10-31 at 12 37 08@2x" src="https://user-images.githubusercontent.com/3261185/139593520-583862be-cb85-4860-a6ed-50ad2e09d7ba.png">

Any ideas what I might be doing wrong?

**To Reproduce**

1. Installed Reach with curl command
2. index.rsh contains the below code only
```
'reach 0.1';
```
3. Running `./reach compile` is successful
4. `npm install @reach-sh/stdlib`
5. Try to import into JS file with code: `import * as reach from '@reach-sh/stdlib/ALGO';`
6. Get error in console

**Expected behavior**

The library is imported successfully with no errors.

**Extra information**

reach v0.1.6
node v16.4.0

**Comment by DanBurton** [comment]
That copy of our tutorial is not hosted or updated by us. See our copy instead:

https://docs.reach.sh/tut-9.html

Specifically, notice the difference in what that old version recommends:

```js
// You need to provide your own web shim for `net` for this to work; not recommended.
import * as reach from '@reach-sh/stdlib/ALGO';
```

Versus what our up-to-date version recommends:

```js
// This will work as expected.
import {loadStdlib} from '@reach-sh/stdlib';
const reach = loadStdlib(process.env);
```

See [the docs for loadStdlib](https://docs.reach.sh/ref-frontends-js-loader_mjs.html#%28javascript._%28%28load.Stdlib%29%29%29) for details.
