### ISSUE TITLE
Tutorial 3 - Rock, Paper, and Scissors - Deprecation warning deploy & attach

### ISSUE THREAD

**Issue by AWolf81** [reach-sh/reach-lang#405]
**Describe the issue**

I've followed the tutorial and started the example with `REACH_CONNECTOR_MODE=ALGO ./reach run` and received two deprecation warnings one for `deploy` and the second for `attach`.

**To Reproduce**

The tutorial code from Github will show them.

Example output:

```
WARNING: acc.deploy(bin) is deprecated; use acc.contract(bin) instead. Deployment is implied by the first publication.
WARNING: acc.attach(bin, info) is deprecated; use acc.contract(bin, info) instead. Attachment is implied by reception of the first publication.
Alice played Paper
Bob played Paper
Bob saw outcome Draw
Alice saw outcome Draw
```

**Expected behavior**

The program should run without a deprecation warning.

**Extra information**

What version of Reach are you using? You can run `reach version` or `reach hashes` to find out.
reach 0.1.7

**Possible fix**
By replacing 

```js
const ctcAlice = accAlice.deploy(backend);
const ctcBob = accBob.attach(backend, ctcAlice.getInfo());
```
with

```js
const ctcAlice = accAlice.contract(backend);
const ctcBob = accBob.contract(backend, ctcAlice.getInfo());
```

The program is working as expected without a deprecation warning. 
I'm new to Reach but if this fix is OK. Please let me know. 
I'd like to update tut 3 through 9 with this change and create a PR.

**Comment by jeapostrophe** [comment]
Yes, that's what the update should be. It would definitely be appreciated if you submitted a PR, but don't feel like you have to. We're actually getting ready to launch a new version of the docs, so we've been a little light on the updates to it. If you are just nervous about the warning, there's no problem at all with using the `deploy/attach` version. :)
