### ISSUE TITLE
API call is failing in latest version

### ISSUE THREAD

**Issue by kodisj** [reach-sh/reach-lang#420]
Reach Hashes:

reach: b34d92ae
reach-cli: b34d92ae
react-runner: b34d92ae
rpc-server: b34d92ae
runner: b34d92ae
devnet-algo: b34d92ae

Checked 205 theorems; No failures!
reachc: The compiler has encountered an internal error:

  The Solidity compiler failed with the message:
Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> /tmp/reachc-sol-6b1f033ee1eec02c/compiled.sol

Error: Invalid type for argument in function call. Invalid implicit conversion from address to address payable requested.
   --> /tmp/reachc-sol-6b1f033ee1eec02c/compiled.sol:791:38:
    |
791 |     _vt._contractAPI_withdraw0 = T13(_a0, _a1);
    |                                      ^^^

This error indicates a problem with the Reach compiler, not your program. Please report this error, along with the pertinent program, to the Reach team as soon as possible so we can fix it.

**Comment by chrisnevers** [comment]
Thanks for opening this issue @kodisj 

Are you calling an API with an `Address` in its domain? If so, I pushed a fix for this issue, but it has not been released yet. If not, could you share your program with me? You can paste it here or DM it to Chris Nevers#6510 in our Discord.

Thanks,
Chris

**Comment by kodisj** [comment]
My discord alias is @enthuGuy.  Sent a friend request for DM.  Please accept it. I will send you the code.

**Comment by chrisnevers** [comment]
Hi @kodisj , we just made a release, `1bd49d90`, that should fix this issue. Can you confirm that it's been resolved?

**Comment by jeapostrophe** [comment]
I'll close this. Please let me know if we need to reopen.
