### ISSUE TITLE
API Participants cannot interact with Map (Local storage)

### ISSUE THREAD

**Issue by tomxbacked** [reach-sh/reach-lang#446]
**Describe the error**

Map used to store indexes of an array, e.g
```
const stakeIndexes = new Map(UInt);
...
.api(
      StakingAPI.stakeAsset,
      ...
      stakeIndexes[this] = userIndex;
...
.api(
      StakingAPI.unstakeAsset,
      ...
      assume(
          isSome(stakeIndexes[this]),
       );
       ...
       // Always triggered regardless if user has previously staked (and should exist in map.)
       require(isSome(
          stakeIndexes[this]
        ), 'User must have staked before unstaking.');
       ...
```

The implementation compiles but the API users seem to be unable to access the map without any compilation or runtime errors.

**To Reproduce**

Contact `thinc#5902` (in reach discord) for reach file.

**Expected behavior**

API participant should be able to query map, and set map in rerquire and generally 

Require statement should check map correctly etc.

**Extra information**
```
$ ./src/reach version
reach 0.1.7
```
```
$ ./src/reach hashes
reach: b34d92ae
reach-cli: b34d92ae
react-runner: b34d92ae
rpc-server: b34d92ae
runner: b34d92ae
devnet-algo: b34d92ae
devnet-cfx: b34d92ae
devnet-eth: b34d92ae
```

**Comment by AwolDes** [comment]
Bumping this - it is effecting me too on a later version `1bd49d90`

An API that looks like this cannot read updates to the `Map` object with that key:
```javascript
.api(
      UserAPI.updateData
      (data) => {
        const user = fromSome(userData[this], {
          name: 'dummy data'
        });
        assume(user.name !== 'dummy data');
```
Will not read the **updated** local state (on the Algorand network), and will still return the `dummy data` default object.

However I can see that this `userData` definitely exists using the following view function
```javascript
State.readUser.set((addr) => userData[addr]
```
