### ISSUE TITLE
REACH_CONNECTOR_MODE environment variable Missing error message

### ISSUE THREAD

**Issue by gpucc** [reach-sh/reach-lang#448]
on **Ubuntu 21.10** using **Reach 0.1.7**

I'm new to REACH and just getting started following the official reach tutorials.

I am getting an error message about the REACH_CONNECTOR_MODE in /root/.config

**./reach config** prompts to set **1 for ALGO**.  Done.    **. /root/.config** as root.  Done.
The change has no effect and ./reach run  returns the same REACH_CONNECTOR_MODE error.

I have tried rebooting Ubuntu and following the steps as root to no avail.  Any work arounds for this?  can the export environment variable be added into a .rsh file instead?

**Comment by jeapostrophe** [comment]
Hi @gpucc ! 

Are you logging in as `root` or are you running `reach` with `sudo`? If the answer is the second, then that's probably the source of the problem, and you also should never use `sudo` with the `reach` tool.

What command are you running, exactly, that gives you this error message?

**Comment by Confucian-e** [comment]
$ REACH_CONNECTOR_MODE=ETH ./reach run
my env is ETH, you just need replace your env

**Comment by jeapostrophe** [comment]
Let me know if you'd like to reopen this.
