### ISSUE TITLE
Improving returning a Map from a View

### ISSUE THREAD

**Issue by AwolDes** [reach-sh/reach-lang#456]
This is a small bug / ergonomic issue. Take this API function:

```javascript
readLocalState: Fun([Address], Object(state))
```
In a `define` block of a `parallelReduce` I set it to this:

```javascript
State.readLocalState.set((addr) => fromSome(localStates[addr], defaultObj);
```

This compiles fine, but causes a variable `undefined` error before a participant publishes, prior to the parallel reduce. I believe this is because Reach is still optimizing retrieval of `Views`.

Instead I must do this:

```javascript
readLocalState: Fun([Address], Data({ None: Null, Some: Object(state) }))
// in define step
State.readLocalState.set((addr) => localStates[addr]);
```

And it works, but it isn't as nice to read, especially on the frontend. Need to do something like `data[1][1]` for the data, because it comes back like this:
```javascript
["Some", ["Some", {data}]]
```

**Comment by jeapostrophe** [comment]
I will investigate this. The `undefined` thing sounds really weird to me, if I can't reproduce, will you send me a sample that does this?

On the double `Some`, I think you want unsafe views --- https://docs.reach.sh/frontend/#ctcunsafeviews

**Comment by AwolDes** [comment]
@jeapostrophe happy to send a code sample for the bug I am experiencing.

I'll give unsafe views a go, but I do like how a `Maybe` type works on the frontend, rather than catching an error as outlined for an unsafe view. Again, this is just an ergonomic request; not critical.

**Comment by jeapostrophe** [comment]
I've modified my test suite to mimic this pattern:

https://github.com/reach-sh/reach-lang/commit/740f8b8472d7b4b548316b7df949bfc16c85c44a#diff-00e1adf8b6f3be81ccc73d5023cd1b022ff0d9ada9735c026c983f7d0660b28fR22-R23

This suggest that either the problem is more complicated and the use of `fromSome` is a red-herring, or that I fixed it while doing other things

**Comment by AwolDes** [comment]
@jeapostrophe will test with latest version after it is released.

**Comment by AwolDes** [comment]
Resolved by updating `stdlib` version & updating to latest Reach release.
