### ISSUE TITLE
can't run ./reach version successfully

### ISSUE THREAD

**Issue by Confucian-e** [reach-sh/reach-lang#473]
**Describe the error**

I have download reach but when I run ./reach version it shows that 
`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/json?filters=%7B%22reference%22%3A%7B%22reachsh%2Freach-cli%3Alatest%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied`
![reach error](https://user-images.githubusercontent.com/46948182/147431418-e63dfd07-9c0e-4a21-a46c-d4a20382ff10.png)

**To Reproduce**

when I run `./reach version`, it shows that
`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/json?filters=%7B%22reference%22%3A%7B%22reachsh%2Freach-cli%3Alatest%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied`

**Expected behavior**

Should't show which version I have installed?

**Extra information**

I just download reach right now.

**Comment by Confucian-e** [comment]
My OS is Ubuntu 20.04 LTS. Looking forward to your answer.

**Comment by Confucian-e** [comment]
Thank you sir, I have solved.

**Comment by ruifortes** [comment]
I was looking forward for your solution :-\
