### ISSUE TITLE
Incorrect gas estimation on Conflux

### ISSUE THREAD

**Issue by Thegaram** [reach-sh/reach-lang#475]
**Overview**

When running the Rock, Paper, Scissors example #9 (web interface), and accepting the wager with Bob, the transaction will use an incorrect gas limit and thus it will fail. [[tx]](https://testnet.confluxscan.io/transaction/0xac259f70a4e5c2a44a2b7c3f1d05a6bdf327fd93514a3cabdaa2d178e0b1292f)

**Root cause**

Executing a `cfx_estimateGasAndCollateral` RPC call using the `from`, `to`, `value`, and `data` fields copied from a failing transaction, we see that it in fact yields the correct gas limit:

```sh
$ curl -X POST --data '{"method":"cfx_estimateGasAndCollateral","id":1,"jsonrpc":"2.0","params":[{"from":"cfxtest:aatzen8jw12p51gtukg8sg07nvvuzv0g62g5rc6fm5","to":"cfxtest:ace80sreg77pr6tnw1bj607mvgbrw2xhva538f2krp","data":"0x2c10a15900000000000000000000000000000000000000000000000000000000044f31d20000000000000000000000000000000000000000000000000000000000000000", "value": "0x29A2241AF62C0000" }]}' -H "Content-Type: application/json" https://test.confluxrpc.com | jq

{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "gasLimit": "0x19a7d", // 105085
    "gasUsed": "0x133de",  // 78814
    "storageCollateralized": "0x180" // 384
  }
}
```

Enabling debug output on the reach side, we see the following output:

```
'DEBUG:' 'addEstimates 1: start:' {from: 'CFXTEST:AATZEN8JW12P51GTUKG8SG07NVVUZV0G62G5RC6FM5', value: '3000000000000000000'}
'DEBUG:' 'addEstimates 2:  orig:' {gas: 0n, storage: 0n}
'DEBUG:' {0: 'XTES', 1: 'send', 2: '_reach_m1', 3: Array(2), 4: 'SEND', kind: 'reach', funcName: '_reach_m1', args: Array(1), value: X,
'DEBUG:' 'addEstimates 3:   est:' 
{
    "est": {
        "gasLimit": "70666",
        "gasUsed": "53000",
        "storageCollateralized": "0"
    }
}
'DEBUG:' 'addEstimates 4: eused:' {gas: 53000n, storage: 0n}
'DEBUG:' 'addEstimates 5:  non0:' {gas: 53000n, storage: 2048n}
...
```

This, and the following code snippet shows that the transaction object passed to `estimateGasAndCollateral` only contains the `from` and `value` fields, which results in an incorrect estimation. It should also contain the `to` and `data` fields.

https://github.com/reach-sh/reach-lang/blob/1c445772b0b4c516195fc0012296a209e7d01046/js/stdlib/ts/cfxers.ts#L242-L246

Reach also uses a very high fallback storage limit (2048). The sender will not be charged for unused storage. However, this will lead to large transaction prices being displayed in Portal, as it displays the "worst case" cost.

**Steps to fix**

Include all 4 fields (`from`, `to`, `value`, `data`) in the call to `estimateGasAndCollateral`. Use `gasLimit` and `storageCollateralized` from the returned object.

**Steps to reproduce**

1. Clone this repo and navigate into `examples/rps-9-web`.
2. Add the line `reach.setProviderByName('TestNet');` in `index.js`.
3. Run the application using `REACH_CONNECTOR_MODE=CFX-browser REACH_DEBUG=1 ./reach react`.
4. Act in one browser as deployer and deploy a new instance.
5. Attach to this contract instance in another browser and accept the proposed wager.
6. Confirm the transaction. It will fail due to `Insufficient gas fee`.
7. Inrease the gas limit and send it again. Now it passes.

**Comment by jeapostrophe** [comment]
Thank you!!!
