### ISSUE TITLE
no docker

### ISSUE THREAD

**Issue by gsmachado** [reach-sh/reach-lang#501]
Hello,

Imagine using `reach` within a docker image...

In order to avoid the DiD hell (docker-in-docker), how can I run `reach` without requiring `docker` nor `docker-compose`? Is there a way to instruct the `reach` bin to find the path of tools and manage their lifecycle, etc?

Please, give me some light on it!

Much appreciated.

**Comment by jeapostrophe** [comment]
If you run `reach` --- https://github.com/reach-sh/reach-lang/blob/master/reach --- with `REACH_DOCKER=0`, then it won't use Docker, but will instead get everything from the repository/PATH. We do not support this at this time, however.
