### ISSUE TITLE
Cost Output Positioning

### ISSUE THREAD

**Issue by AwolDes** [reach-sh/reach-lang#508]
Recently an update was made that outputs text used to visualize the program using something like https://dreampuf.github.io/GraphvizOnline

This output is 100+ lines for me and when optimizing cost for Algorand is a bit annoying scrolling every compile to see the new cost.

Can the expensive path output at the bottom also include the cost?

```diff
+ Most expensive path cost: 801
to see the path:
     TOP --25--> normal --6--> preamble --15--> ...
```

**Comment by jeapostrophe** [comment]
It is now in a file that you get when you run with intermediate files or debugging
