### ISSUE TITLE
Feature Request: Batch retrieval of address balances

### ISSUE THREAD

**Issue by AwolDes** [reach-sh/reach-lang#551]
Currently on a frontend you can call `reach.balanceOf(addr)` and get the network token balance back. Similar to this, you can do `reach.balanceOf(addr, tokA)` and get the balance of `tokA`.

I propose a new function call `reach.balancesOf(addr, [networkTok, tokA, tokB]` that can get this information in a single network request, rather than multiple. This has much better client side performance

**Comment by jeapostrophe** [comment]
Added by #564 ; thanks for the suggestion!
