### ISSUE TITLE
Feature Request:  Support MetaData and MetaDataHash in stdlib launchToken

### ISSUE THREAD

**Issue by zonedotgame** [reach-sh/reach-lang#585]
**Describe the error**

When i use stdlib.launchToken("Name","Unit",{supply:1,decimals:0}), it creates an ASA in algorand but not taking metaData and metaDataHash as input and supplies it to asset create txn function of algoSDK.

**To Reproduce**

Call stdlib.launchToken with metaData and metaDataHash in opts, it will be ignored.

**Expected behavior**

It should take both metaData and metaDataHash and pass it to algosdk to make it fully functional utility

**Extra information**

0.1.8-rc.9, changes are marked with // Add this line and // Change this line

Here is the modified code of launchToken function

async function launchToken (accCreator, name, sym, opts = {}) {
  console.log(`Launching token, ${name} (${sym})`);
  const addr = (acc) => acc.networkAccount.addr;
  const caddr = addr(accCreator);
  const zaddr = caddr;
  // ^ XXX should be nothing; docs say can be "", but doesn't actually work
  //const client = await getAlgodClient();
  //const p = await stdlib.makeProviderByEnv(process.env);
 // const client = await stdlib.getProvider().algodclient
 
  const dotxn = async (mktxn, acc = accCreator) => {
    const sk = acc.networkAccount.sk;
    if ( ! sk ) {
      throw new Error(`can only launchToken with account with secret key`);
    }
    const params = await stdlib.getTxnParams('launchToken');
    const t = mktxn(params);
    const s = t.signTxn(sk);
    const r = (await client.sendRawTransaction(s).do());
    return await waitForConfirmation(r.txId);
  };
  const supply = opts.supply ? stdlib.bigNumberify(opts.supply) : stdlib.bigNumberify(2).pow(64).sub(1);
  const decimals = opts.decimals !== undefined ? opts.decimals : 6;
  ****const metaData = opts.metadata;                   //Add this line
  const metaDataHash = opts.metaDataHash;**  // Add this line**
  const ctxn_p = await dotxn(
    (params) =>
    algosdk.makeAssetCreateTxnWithSuggestedParams(
      caddr, undefined, bigNumberToBigInt(supply), decimals,
      false, zaddr, zaddr, zaddr, zaddr,
      ****sym, name, metaData, metaDataHash, params,**   // Change this line**
    ));
  const idn = ctxn_p['created-asset-index'];
  if ( ! idn ) { throw Error(`${sym} no asset-index!`); }
  const id = stdlib.bigNumberify(idn);
  console.log(`${sym}: asset is ${id}`);

  const mint = async (accTo, amt) => {
    console.log(`${sym}: transferring ${amt} ${sym} for ${addr(accTo)}`);
    await transfer(accCreator, accTo, amt, id);
  };
  const optOut = async (accFrom, accTo = accCreator) => {
    await dotxn(
      (params) =>
      algosdk.makeAssetTransferTxnWithSuggestedParams(
        addr(accFrom), addr(accTo), addr(accTo), undefined,
        0, undefined, idn, params
      ), accFrom);
  };
  return { name, sym, id, mint, optOut };
};

**Comment by jeapostrophe** [comment]
We will do this soon

**Comment by jeapostrophe** [comment]
@erer1243 just pushed this, it will be in the next release
