### ISSUE TITLE
Const defined in DEFINE_BLOCK but used in other causes error in strict mode

### ISSUE THREAD

**Issue by MetaB0y** [reach-sh/reach-lang#620]
If I create a const in `DEFINE_BLOCK` of `parallelReduce` and then use it in `PAY_EXPR` of `.api` of `parallelReduce` in strict mode, then the contract is not compiled because of error[RE0094]: unused variable.

The variable can be accessed normally.

reach 0.1.8 (reach: 85500c11)

**Comment by jeapostrophe** [comment]
This error was fixed in the next release, bf654a17, from February 15th
