### ISSUE TITLE
Problem with Reach compiler

### ISSUE THREAD

**Issue by kshirsagardeepika** [reach-sh/reach-lang#677]
Using API to transfer nft to buyer and written as follows
const Buyer = API('Buyer', {
        buy: Fun([Token, UInt], Null),
});
const [done] = parallelReduce([false])
        ...
        .api(Buyer.buy,  
            (nftid, x, k) => {
            k(null);
            transfer(x).to(Creator);
            transfer(x, nftid).to(this);
            return [ done ];
        })
      ...
on compiling program received below error: 
The compiler has encountered an internal error:
  fluid ref unbound: FV_tokens at: index.rsh
This error indicates a problem with the Reach compiler, not your program. Please report this error, along with the pertinent program, to the Reach team as soon as possible so we can fix it.

CallStack (from HasCallStack):
  error, called at src/Reach/Util.hs:84:3 in reach-0.1.8-6Xz7mGsYzW2Hfnpf7MuZz4:Reach.Util
  impossible, called at src/Reach/Linearize.hs:360:16 in reach-0.1.8-6Xz7mGsYzW2Hfnpf7MuZz4:Reach.Linearize

**Comment by jeapostrophe** [comment]
Can you please upgrade to the newer version of Reach and confirm that this still a problem? (0.1.9 came out yesterday and I fixed a related problem.)

**Comment by kshirsagardeepika** [comment]
Update resolved issue but now getting error as
![reach-error](https://user-images.githubusercontent.com/78475108/157890272-c255912d-65ff-433e-8a71-0bd213533847.png)
and updated  transfer(x, nftid).to(this); to transfer([x, [x,nftid]]).to(this);
but in both cases getting same error.

Please provide some solution, Thanks

**Comment by jeapostrophe** [comment]
Your program is wrong and the message tells you what is wrong. Your invariant is too weak and doesn't ensure that there are funds in the account to do the transfer.
