### ISSUE TITLE
reach run cannot find Python library

### ISSUE THREAD

**Issue by MetaB0y** [reach-sh/reach-lang#687]
I have a problem with the new reach 0.1.9. When I do `./reach run`, I get 
```
Step 3/3 : CMD ["index"]
 ---> Running in ea95b8082adb
Removing intermediate container ea95b8082adb
 ---> 294ddb63f84a
Successfully built 294ddb63f84a
Successfully tagged reachsh/reach-app-temp:0.1.9
[1792110] Error loading Python lib '/tmp/reach.2022-03-16T10-48-01Z-tXEt/_MEIueImV2/libpython3.7m.so.1.0': dlopen: libcrypt.so.1: cannot open shared object file: No such file or directory
```
`./reach update` does not help.

Previously (reach 0.1.8) it worked fine I think.

There is a dir `/tmp/reach.2022-03-16T10-48-01Z-tXEt` but it doesn't even have `_MEIueImV2` subdir.

I run Manjaro Linux.

**Comment by mattaudesse** [comment]
This doesn't sound like a Reach issue but we can test whether 0.1.9 vs. 0.1.8 is the problem - does it work if you run:

``` sh
REACH_VERSION=0.1.8 ./reach run
```

instead?

If it still fails I'd suggest `--force` reinstalling your `docker-compose` and `python3.7` packages on this machine... It looks like they're the more likely culprits.

**Comment by mattaudesse** [comment]
@MetaB0y I'm going to close since this doesn't sound like a Reach issue.

**Comment by MetaB0y** [comment]
> @MetaB0y I'm going to close since this doesn't sound like a Reach issue.

Yeah, you are right, I was just confused with the temp directory name. My `docker-compose` was broken somehow. 

Thanks!
