### ISSUE TITLE
Cannot dynamically load @reach-sh/stdlib/ALGO_WalletConnect in a NextJS web application

### ISSUE THREAD

**Issue by lorenzopolidori** [reach-sh/reach-lang#710]
**Describe the error**

Nextjs web applications use Server Side Rendering (SSR) by default. This means that app dependencies are compiled and bundled in a node environment on the backend before generating the web pages and returning the HTML code to the browser. When doing so, the `window` object - that is normally available on a browser javascript environment - is not defined.

I have created a simple nextjs app and installed reach:

```bash
npx create-next-app --use-npm
npm install @reach-sh/stdlib
```

In the `index.js` file I imported reach and the wallet dependencies at the top:

```js
import { loadStdlib } from '@reach-sh/stdlib';
import MyAlgoConnect from '@reach-sh/stdlib/ALGO_MyAlgoConnect';
```

If I now run the app on a dev server:
```
npm run dev
```

I get this error message on the console:

```
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

This happens because one of the dependencies of the `MyAlgoConnect` library uses `window` in its implementation:

```
at Messenger._installListener (/node_modules/@randlabs/communication-bridge/lib/messenger.js:144:3)
at new Messenger (/node_modules/@randlabs/communication-bridge/lib/messenger.js:43:8)
at new Messaging (/node_modules/@randlabs/myalgo-connect/lib/messaging/Messaging.js:56:17)
```

I can solve this problem by dynamically loading `MyAlgoConnect` instead of compiling and bundling it into the app before generating the page. This way `MyAlgoConnect` will run within the browser context and `window` will be available to use.

I changed the `index.js` file to dynamically import all Reach client libraries:

```js
import Head from 'next/head'
import { useRef, useState, useEffect } from 'react'

export default function Home() {
  const reach = useRef()
  const myAlgoConnect = useRef()
  const [loading, setLoading] = useState(true)

  async function connectMyAlgoWallet() {
    setWallet({ MyAlgoConnect: myAlgoConnect.current })
    await connectWallet()
  }

  function setWallet(wallet) {
    reach.current.setWalletFallback(reach.current.walletFallback({
      providerEnv: 'TestNet', ...wallet
    }))
  }

  async function connectWallet() {
    let account;
    try {
      account = await reach.current.getDefaultAccount()
    } catch (e) {
      console.error('Error when connecting to wallet', e)
      return;
    }
    const balance = await reach.current.balanceOf(account)
    reach.current.formatCurrency(balance, 4)
  }

  useEffect(() => {
    async function loadLibs() {
      let [reachStdlib, myAlgoConnectLib] = await Promise.all([
        import('@reach-sh/stdlib'),
        import('@reach-sh/stdlib/ALGO_MyAlgoConnect')
      ])
      reach.current = reachStdlib.loadStdlib({ ...process.env, 'REACH_CONNECTOR_MODE': 'ALGO' })
      myAlgoConnect.current = myAlgoConnectLib.default
      setLoading(false)
    }
    loadLibs()
  }, [])

  return (
    <div className="container">
      <Head>
        <title>Algorand Wallets with NextJS and Reach</title>
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main>
        <h1>Algorand Wallets with NextJS and Reach</h1>
        <header>NextJS React web application to allow users to connect to their Algorand wallets using the reach client library.</header>

        <nav>
          {loading && <div>Loading...</div>}
          {!loading && <button onClick={connectMyAlgoWallet}>Connect to MyAlgo</button>}
        </nav>
      </main>
    </div>
  )
}
```

This now works as expected. It also has the advantage of loading and rendering the static page very quickly, while the Reach client libraries are downloaded in the background. 
Loading `stdlib` and `ALGO_MyAlgoConnect` in parallel is also a further optimization and it works with no issues.

I later tried to add support for WalletConnect, which would enable using Pera Wallet.

If I try to dynamically load `ALGO_WalletConnect` library in parallel with `stdlib` and `ALGO_MyAlgoConnect` in `useEffect`, as follows:

```js
let [reachStdlib, myAlgoConnectLib, walletConnectLib] = await Promise.all([
    import('@reach-sh/stdlib'),
    import('@reach-sh/stdlib/ALGO_MyAlgoConnect'),
    import('@reach-sh/stdlib/ALGO_WalletConnect')
])
```

I get the following error:

```
shared_backend.mjs?fa3d:187 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'utils')
    at eval (shared_backend.mjs?fa3d:187:10)
    ...
    at eval (ALGO_WalletConnect.mjs:4:70)
    at Module../node_modules/@reach-sh/stdlib/ALGO_WalletConnect.mjs (node_modules_reach-sh_stdlib_ALGO_WalletConnect_mjs.js:2825:1)
    ...
    at async Promise.all (:3000/index 2)
```

It seems that `ALGO_WalletConnect` cannot find a `utils` variable used in `shared_backend.mjs`.
This might be because of missing dependencies defined in reach `stdlib`, so I tried to dynamically load `ALGO_WalletConnect` after `stdlib` is fully loaded, as below:

```js
useEffect(() => {
    async function loadLibs() {
      let [reachStdlib, myAlgoConnectLib] = await Promise.all([
        import('@reach-sh/stdlib'),
        import('@reach-sh/stdlib/ALGO_MyAlgoConnect')
      ])
      reach.current = reachStdlib.loadStdlib({ ...process.env, 'REACH_CONNECTOR_MODE': 'ALGO' })
      myAlgoConnect.current = myAlgoConnectLib.default

      let walletConnectLib = await import('@reach-sh/stdlib/ALGO_WalletConnect')

      setLoading(false)
    }
    loadLibs()
}, [])
```

but with no luck, I still get the same error.

**To Reproduce**

Clone this sample NextJS app and run `npm run dev` to reproduce the error: https://github.com/lorenzopolidori/nextjs-reach-wallet-connect

**Expected behavior**

`@reach-sh/stdlib/ALGO_MyAlgoConnect` should dynamically load with no errors.

**Extra information**

`@reach-sh/stdlib` version `0.1.9-rc.5`.

**Comment by jeapostrophe** [comment]
I hope that once we merge #664 it will work, but in the meantime I wonder if making stdlib not dynamic but the other two dynamic will work for you?

**Comment by jeapostrophe** [comment]
On the next release, it should be possible for you to re-check this

**Comment by lorenzopolidori** [comment]
> I hope that once we merge #664 it will work, but in the meantime I wonder if making stdlib not dynamic but the other two dynamic will work for you?

Unfortunately, even if I statically `import { loadStdlib } from '@reach-sh/stdlib'`  and then use `let walletConnectLib = await import('@reach-sh/stdlib/ALGO_WalletConnect')` in `useEffect()`, I still get the same error: "TypeError: Cannot read properties of undefined (reading 'utils')".

**Comment by jeapostrophe** [comment]
Well, we haven't done a release yet, so I don't expect anything to be different. We normally do releases on Thursday

**Comment by lorenzopolidori** [comment]
It seems `0.1.9-rc.6` has made things even worse with Next.js. 

`await import('@reach-sh/stdlib/ALGO_WalletConnect')` still gives the same error as before:
```
Error when loading ALGO_WalletConnect TypeError: Cannot read properties of undefined (reading 'utils')
```
In addition to that, I can't open the AlgoWallet anymore. When I call `stdlib.getDefaultAccount()` I get this error:
```
Error: Constructing MyAlgoConnect with the non-webpacked version of @reach-sh/stdlib is not supported.
```
This is reproducible cloning this repo: https://github.com/lorenzopolidori/nextjs-reach-wallet-connect/tree/reach-0.1.9-rc.6
(branch `reach-0.1.9-rc.6`) and running `npm run dev`.

This is statically importing all libraries, as in:
```js
import { loadStdlib } from '@reach-sh/stdlib';
import MyAlgoConnect from '@reach-sh/stdlib/ALGO_MyAlgoConnect';
const stdlib = loadStdlib({ ...process.env, 'REACH_CONNECTOR_MODE': 'ALGO' });
```

**Comment by lorenzopolidori** [comment]
The same error happens with dynamically loaded reach libraries.
To reproduce, clone https://github.com/lorenzopolidori/nextjs-reach-wallet-connect/tree/reach-0.1.9-rc.6-dynamic (branch reach-0.1.9-rc.6-dynamic) and run `npm run dev`.

**Comment by DanBurton** [comment]
@lorenzopolidori

Instead of this:

```
import { loadStdlib } from '@reach-sh/stdlib';
import MyAlgoConnect from '@reach-sh/stdlib/ALGO_MyAlgoConnect';
```

Can you try this?

```
import { loadStdlib } from '@reach-sh/stdlib';
import { ALGO_MyAlgoConnect as MyAlgoConnect } from '@reach-sh/stdlib';
```

That should give you the webpacked version of it that the error message is talking about.

This is a recent change, and we have updated our docs to recommend the new way of importing it.

**Comment by lorenzopolidori** [comment]
Thanks! I didn't see the updated docs, it works beautifully now with `reach-0.1.9-rc.6`, even with dynamic loading:
```js
const reach = useRef()
const myAlgoConnect = useRef()
const walletConnect = useRef()
const [loading, setLoading] = useState(true)

useEffect(() => {
    async function loadLibs() {
      const reachStdlib = await import('@reach-sh/stdlib')
      reach.current = reachStdlib.loadStdlib({ ...process.env, 'REACH_CONNECTOR_MODE': 'ALGO' })
      myAlgoConnect.current = reachStdlib.ALGO_MyAlgoConnect
      walletConnect.current = reachStdlib.ALGO_WalletConnect
      setLoading(false)
    }
    loadLibs()
}, [])
```

**Comment by jeapostrophe** [comment]
Boom!
