### ISSUE TITLE
minimumBalanceOf func may require revision

### ISSUE THREAD

**Issue by temptemp3** [reach-sh/reach-lang#756]
**Describe the error**

For account https://testnet.algoexplorer.io/address/4C3WDVXYY3ARRUER5XMXSTYHFNBFLSW4VWQYSLXTDEZJP33GPRFR7MEVYQ
minimumBalanceOf is reported as '2' where it should be 2.7.
May be missing 100000u per extra page

**To Reproduce**

Please include the program(s) that produce the unexpected behavior from Reach. If the error is in the compiler or during verification, you just need to include the `.rsh` file. If it is while the program is running, you should also include the `.mjs` file. It is easiest to link the file after posting them on `gist.github.com`, but if you don't want to share them publicly, please contact Jay McCarthy on our Discord server --- https://discord.gg/AZsgcXu --- and get them to him privately or he can help you reduce the code.

WIP

**Expected behavior**

minimumBalanceOf will return 2.7

**Extra information**

`REACH_VERSION=402c3faa`

v0.1.9-rc4

**Comment by jeapostrophe** [comment]
I think our plan is to merge this --- https://github.com/reach-sh/reach-lang/pull/671 --- once the indexer adds the field and then be done with it

**Comment by temptemp3** [comment]
@jeapostrophe cool thx. FYI, purestake api has the field. May help to validate. For calcs, I believe we missed extra pages. 
Anyways, that works. We can go ahead and close this. Thx!
