### ISSUE TITLE
LaunchToken does not support note field for Algorand, which is the killer feature for Algorand NFT Galleries

### ISSUE THREAD

**Issue by KodisBabu** [reach-sh/reach-lang#780]
**Describe the error**

Most of the Algorand NFT galleries take the metadata from note field of the algorand minted token instead of IPFS url

**To Reproduce**

I have tested both IPFS url and Note field in many galleries,  Note field metadata is supported in many galleries.  

**Expected behavior**

Allow LaunchToken() call to take note field as optional param and pass it to algosdk asset creation call.

**Extra information**

0.1.9

Could you please support notes field in launchToken for algorand ?  That would make the launch token utility a fantastic one for algorand NFTs.

// signing and sending "txn" allows "addr" to create an asset

    let txn = algosdk.makeAssetCreateTxnWithSuggestedParamsFromObject({"from":addr, "note":note,manager,reserve,
    "total":totalIssuance, "decimals":decimals, "defaultFrozen":defaultFrozen,unitName, assetName, assetURL, assetMetadataHash, "suggestedParams":params});

var JsonToArray = function(json)
{
    var str = JSON.stringify(json, null, 0);
    var ret = new Uint8Array(str.length);
    for (var i = 0; i < str.length; i++) {
        ret[i] = str.charCodeAt(i);
    }
    return ret
};

note = JsonToArray(metaDataJson);
This is what i have done in my code, it is working fantastic for algo NFTs in galleries.

**Comment by jeapostrophe** [comment]
First, none of the ARC standards for NFTs use the Note field for anything --- https://github.com/algorandfoundation/ARCs/tree/main/ARCs --- It is limited at 1024 and thus brittle. I think that you should file issues with the NFT galleries in question or investigate further what is really happening. For example, if you look at

https://www.randgallery.com/algo-collection/?address=614446116

which was minted here

https://algoexplorer.io/tx/TXIPVJICSLPPB5UQUWZF3UXG2TKPDTNVQBM7R2XUVN2DNGRB3QNQ

You'll see that it does look at IPFS, as the ARC standard says to.

Second, this is about to be fixed.
