### ISSUE TITLE
remote.fun.stake.pay(PAY_EXPR)(tokenAmount) throws logic eval error: itxn_begin without itxn_submit

### ISSUE THREAD

**Issue by MetaB0y** [reach-sh/reach-lang#843]
This is a follow-up for https://github.com/reach-sh/reach-lang/issues/812, I believe one of the issues was not fixed. It is still reproducible for me. @jeapostrophe could you take another look? 

I updated the repo: https://github.com/MetaB0y/reach-remote-problems

I use the latest reach 0.1.10rc-1 but had it in 0.1.10rc0 too.

**Comment by MetaB0y** [comment]
Also, I believe there is yet another (third) related issue that is somewhat tricky to reproduce. I will try to do it and upload it to a separate repo.

**Comment by jeapostrophe** [comment]
Thank you, I will look into it.

**Comment by jeapostrophe** [comment]
Thank you for finding this!
