### ISSUE TITLE
remote.fun.withbill([token])() logic eval error: cannot fetch key, <wallet> has not opted in to app <id>.

### ISSUE THREAD

**Issue by MetaB0y** [reach-sh/reach-lang#844]
I have an issue with remote contract interaction.

I get
```
Error: stake errored with Error: API call failed: {
  "type": "signAndPost",
  "e": {
    "status": 400,
    "response": {
      "message": "TransactionPool.Remember: transaction VD2L24KMGUFSULZ7G4UQCDNGUCJDAKRWVNW2ACC2JEWOZJZVXD7Q: logic eval error: logic eval error: cannot fetch key, 4RGLW6HEDFSLEG32LGOUKOYPN6RNPHC3XZVWA76CJISHKZWM2L266NDNDU has not opted in to app 1940. Details: pc=1838, opcodes=extract 18 9\nconcat\napp_local_put\n. Details: pc=290, opcodes=load 254\nitxn_field Assets\nitxn_submit\n"
    }
  },
  "es": "Error: Network request error. Received status 400: TransactionPool.Remember: transaction VD2L24KMGUFSULZ7G4UQCDNGUCJDAKRWVNW2ACC2JEWOZJZVXD7Q: logic eval error: logic eval error: cannot fetch key, 4RGLW6HEDFSLEG32LGOUKOYPN6RNPHC3XZVWA76CJISHKZWM2L266NDNDU has not opted in to app 1940. Details: pc=1838, opcodes=extract 18 9\nconcat\napp_local_put\n. Details: pc=290, opcodes=load 254\nitxn_field Assets\nitxn_submit\n"
}
    at /home/anonymous/github/cometa-contracts/node_modules/@reach-sh/stdlib/dist/cjs/shared_impl.js:306:34
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
when trying to call 
`const stateOfUnderlyingFarm = underlyingFarmCtc.claim.withBill([rewardToken])();` inside API of "wrapper" contract.

I created a repo to highlight this issue: https://github.com/MetaB0y/reach-remote-optin-problem

It seems that for some reason caller contract is not opted in into the callee contract but there is no way to manage this directly.

**Comment by jeapostrophe** [comment]
I do not know how to do this elegantly. It is "easy" to add a way for a remote interface to specify that you'll be doing a call to some function with the `OptIn` `OnCompletion` set. But that is going to increase the minimum balance of the application in a way that is hard to calculate and not possible to do statically AND it is going to require the application to eventually `ClearState` before it gets deleted. I do not know how to do this in a reasonable way.

This will not be fixed anytime soon. 

Here are two things to compensate:
1) Short-run: You can write some hand TEAL code, Y, and have your program X call Y which calls Z. Y would handle these low-level Algorand details

2) Medium-run: Algorand is adding a feature that makes it so application opt-in won't be needed or used anymore by Reach or programs that work like Reach programs.

**Comment by MetaB0y** [comment]
@jeapostrophe Sorry, I am not sure if I understand what is "this" exactly? 

I can interact with other smart contracts on Algorand somehow. Here I have a seemingly simple case in the best environment possible (both contracts were created by me and deployed by me simultaneously).

I do not understand why remote interactions work in some cases on Algorand but in others, they don't. How do I know what is currently possible and what isn't? What separates my example from many other currently possible cases?


Also, is there any rough estimate about the way (2)? Is it more like "this summer" or "some time next year"?

**Comment by jeapostrophe** [comment]
"How do I know what is currently possible and what isn't?"

Algorand has no way to define how to use an application. There is no definition of how a caller C should call an application F. There is no way for you to find out how to call F. There is no way for you to write down what C should do. Reach does not solve this problem for you or Algorand. Thus, the answer is that you cannot know what is possible and what isn't. That is why Reach warns you every time you make a remote call on Algorand. Today, Algorand does not have "composability", which means that C can be written without knowing the implementation details of F.

"What separates my example from many other currently possible cases?"

F requires C to be opted-in. If F were written in Reach, that means that F uses a `Map` and tries to write to the entry of the caller.

"Is there any rough estimate about the way (2)?"

Algorand has not published a release estimate. There is an issue for it --- https://github.com/algorand/go-algorand/issues/3889 --- and my opinion based on nothing is that this will happen before the end of the summer and probably sooner.

**Comment by ThannDev** [comment]
Have you able to resolved your issues?
