### ISSUE TITLE
[Suggestion] expose signTxns on window.algorand (or some workaround to access it)

### ISSUE THREAD

**Issue by grzracz** [reach-sh/reach-lang#856]
It's needed to access TX signature without actually sending it to chain

**Comment by DanBurton** [comment]
I believe the workaround you're looking for is something like:

```
const w = reach.walletFallback({
  providerEnv: 'TestNet',
  MyAlgoConnect,
});
w.signTxns(txns);
```

**Comment by jeapostrophe** [comment]
We believe that does not exist because our fallback only implements signAndPostTxns but could easily implement that... or am I wrong?

**Comment by DanBurton** [comment]
Ohhhh I see. I forgot we don't currently expose that, but that optional interface is in the ARC and is super easy for us to expose. Opened a PR.
