### ISSUE TITLE
Validator does not assume that time is non-decreasing in successive API calls inside `parallelReduce`

### ISSUE THREAD

**Issue by flyingleafe** [reach-sh/reach-lang#862]
**Describe the error**

If I assign a result of `thisConsensusTime`/`lastConsensusTime` to a loop variable inside a `parallelReduce` API call, the validator fails if I add a check that a new value of this variable is GTE than the previous one.

**To Reproduce**

Minimal example: https://github.com/MetaLabsOG/reach-issues/blob/main/time-validation/index.rsh
After uncommenting the marked `check`, I get an error like this:
```
$ reach compile
Verifying knowledge assertions
Verifying for generic connector
  Verifying when ALL participants are honest
Verification failed:
  when ALL participants are honest
  of theorem: require
  at ./index.rsh:26:12:application
  at /app/index.rsh:20:34:application call to [unknown function] (defined at: /app/index.rsh:20:34:function exp)

  // Violation Witness

  const UInt.max = 2;

  const curTime/94 = <loop variable>;
  //    ^ could = 2
  //      from: ./index.rsh:17:35:while
  const thisConsensusTime/108 = <a publication>;
  //    ^ could = 1
  //      from: ./index.rsh:17:35:dot

  // Theorem Formalization

  const v113 = thisConsensusTime/108 >= curTime/94;
  //    ^ would be false
  require(v113);

  Verifying when NO participants are honest
Checked 16 theorems; 1 failures :'(
```

**Expected behavior**

The validation should pass successfully, since the validator should assume that successive calls to `thisConsensusTime`/`lastConsensusTime` inside the `parallelReduce` loop yield non-decreasing values.

**Extra information**

```
$ reach version
reach 0.1.10

$ reach hashes
reach-cli: b3269997
reach: b3269997
react-runner: b3269997
rpc-server: b3269997
runner: b3269997
devnet-algo: b3269997
devnet-cfx: b3269997
devnet-eth: b3269997
```

**Comment by jeapostrophe** [comment]
Thanks, I'll check it out!

**Comment by jeapostrophe** [comment]
When I run your program (with a few line changes) I get
```
Verification failed:
  when ALL participants are honest
  of theorem: require
  at ./users/pr862.rsh:15:12:application
  at /home/jay/Dev/scm/bitbucket.jeapostrophe/r
each/reach-lang/users/pr862.rsh:10:26:applicati
on call to [unknown function] (defined at: /hom
e/jay/Dev/scm/bitbucket.jeapostrophe/reach/reac
h-lang/users/pr862.rsh:10:26:function exp)

  // Violation Witness

  const UInt.max = 2;

  const curTime/90 = <loop variable>;
  //    ^ could = 2
  //      from: ./users/pr862.rsh:7:35:while
  const thisConsensusTime/104 = <a publication>
;
  //    ^ could = 1
  //      from: ./users/pr862.rsh:7:35:dot

  // Theorem Formalization

  const v109 = thisConsensusTime/104 >= curTime
/90;
  //    ^ would be false
  require(v109);

  Verifying when NO participants are honest
```

But that's because you used `check`, which is a `require`, which must be matched with an `assume`. You really meant to use `assert`.

But you still have a problem, the verifier only knows what you tell it. And all it knows about `curTime` is that it is some number. You just need to tell the verifier you expect it to be `thisConsensusTime`

See:

https://gist.github.com/58aab5775734f2e5921cf870e8f0eb1f
