### ISSUE TITLE
Add a possibility to update/downgrade Reach to a particular version (e.g. to a tagged release)

### ISSUE THREAD

**Issue by flyingleafe** [reach-sh/reach-lang#934]
Currently, `reach update` automatically pulls the latest available Reach docker images from Dockerhub.
However, since those images are updated from the current master on a rolling basis (AFAIU), it is easy to end up with the version of Reach which is newer than last released tag, and therefore produces compiled JS code which is incompatible with the latest JS stdlib available in the NPM. Right now, I encounter a following error after doing `reach update` in the project which uses `@reach-sh/stdlib:0.1.10-rc.3`:

```
This Reach compiled JavaScript backend does not match the expectations of this Reach standard library: expected 14, but got 15; update your standard library and rerun!
```

I will have to circumvent this by pinning the necessary version of `@reach-sh/stdlib` to the particular Github commit directly, but I would rather just use the version of Reach which corresponds to the available version of stdlib. However, I do not see an easy way of doing this.

**Comment by jeapostrophe** [comment]
https://docs.reach.sh/tool/#ref-usage-envvar-version
